begin;
create extension if not exists pgtap with schema extensions;
select plan(18);
select extensions.has_table('public','notification_preferences','notification preferences exist');
select extensions.has_table('public','notifications','notification inbox exists');
select extensions.has_table('public','notification_deliveries','notification delivery ledger exists');
select extensions.ok((select relrowsecurity from pg_class where oid='public.notification_preferences'::regclass),'preferences have RLS');
select extensions.ok((select relrowsecurity from pg_class where oid='public.notifications'::regclass),'notifications have RLS');
select extensions.ok((select relrowsecurity from pg_class where oid='public.notification_deliveries'::regclass),'delivery ledger has RLS');
select extensions.ok(not has_table_privilege('anon','public.notifications','select'),'anonymous users cannot read notifications');
select extensions.ok(not has_table_privilege('authenticated','public.notifications','insert'),'clients cannot forge notifications');
select extensions.ok(not has_table_privilege('authenticated','public.notification_deliveries','insert'),'clients cannot forge delivery receipts');
select extensions.ok(not has_table_privilege('authenticated','public.notification_deliveries','update'),'clients cannot forge delivery outcomes');
select extensions.ok(has_table_privilege('authenticated','public.notification_preferences','insert'),'members can create preferences');
select extensions.ok(has_column_privilege('authenticated','public.notifications','read_at','update'),'recipients can mark notifications read');
select extensions.ok(has_function_privilege('authenticated','public.create_announcement_with_notifications(uuid,uuid,text,text,text,public.app_role[],boolean,timestamptz)','execute'),'authenticated users can call guarded publication RPC');
select extensions.ok(not has_function_privilege('anon','public.create_announcement_with_notifications(uuid,uuid,text,text,text,public.app_role[],boolean,timestamptz)','execute'),'anonymous publication is denied');
select extensions.ok(has_function_privilege('authenticated','public.set_notification_preferences(uuid,boolean,boolean,boolean)','execute'),'members can save channel preferences atomically');
select extensions.ok(not has_function_privilege('anon','public.set_notification_preferences(uuid,boolean,boolean,boolean)','execute'),'anonymous preference changes are denied');
select extensions.ok(exists(select 1 from pg_indexes where indexname='notifications_user_unread_idx'),'unread inbox lookup is indexed');
select extensions.ok(exists(select 1 from pg_indexes where indexname='notification_deliveries_retry_idx'),'delivery retry lookup is indexed');
select * from extensions.finish();
rollback;
