"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { isPlatformOwnerEmail } from "@/lib/auth/platform";
import { getPublicEnv } from "@/lib/env";
import { normalizedWebsiteUrl } from "@/lib/platform/portfolio";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { findOrInviteAuthUser } from "@/lib/supabase/users";

const emptyToUndefined = (value: unknown) => String(value || "").trim() || undefined;
const schoolSchema = z.object({
  name:z.string().trim().min(2).max(160), slug:z.string().trim().min(2).max(80).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  legal_name:z.string().trim().max(200).optional(), website_url:z.string().trim().max(500).optional(), school_type:z.enum(["preschool","day_school","day_boarding","boarding","college","other"]), education_board:z.string().trim().max(80).optional(),
  established_year:z.preprocess(emptyToUndefined,z.coerce.number().int().min(1800).max(2200).optional()), affiliation_number:z.string().trim().max(80).optional(), primary_email:z.preprocess(emptyToUndefined,z.string().email().max(254).optional()), primary_phone:z.string().trim().max(30).optional(),
  plan_name:z.string().trim().min(1).max(80), customer_success_owner:z.string().trim().max(160).optional(), billing_cycle:z.enum(["monthly","quarterly","annual"]), recurring_amount:z.coerce.number().nonnegative(), implementation_fee:z.coerce.number().nonnegative(), contract_status:z.enum(["trial","active","paused","expired"]),
  contract_starts_on:z.string().optional(), contract_ends_on:z.string().optional(), licensed_students:z.preprocess(emptyToUndefined,z.coerce.number().int().nonnegative().optional()),
});
const branchSchema=z.object({name:z.string().trim().min(2).max(160),code:z.string().trim().min(2).max(24),address_line1:z.string().trim().min(3).max(240),city:z.string().trim().min(2).max(100),state:z.string().trim().min(2).max(100),postal_code:z.string().trim().max(20),latitude:z.preprocess(emptyToUndefined,z.coerce.number().min(-90).max(90).optional()),longitude:z.preprocess(emptyToUndefined,z.coerce.number().min(-180).max(180).optional()),email:z.preprocess(emptyToUndefined,z.string().email().max(254).optional()),phone:z.string().trim().max(30)});
const ownerSchema=z.object({name:z.string().trim().min(2).max(160),email:z.string().trim().email().max(254).transform(v=>v.toLowerCase()),phone:z.string().trim().max(30),job_title:z.string().trim().max(100)});

function status(kind:"success"|"error",message:string,view="schools"):never { const safeView=["schools","branches","owners","commercials","onboarding"].includes(view)?view:"schools";redirect(`/platform?view=${safeView}&${kind}=${encodeURIComponent(message)}`); }
function schoolStatus(id:string,kind:"success"|"error",message:string,view="overview"):never { const safeView=["overview","metrics","school","branches","owners"].includes(view)?view:"overview";redirect(`/platform/schools/${id}?view=${safeView}&${kind}=${encodeURIComponent(message)}`); }
async function platformUser(){const client=await createClient();const {data:{user}}=client?await client.auth.getUser():{data:{user:null}};if(!user||!isPlatformOwnerEmail(user.email))redirect("/login?next=/platform");return user;}
async function schoolCanBeChanged(admin:NonNullable<ReturnType<typeof createAdminClient>>,organizationId:string){const {data}=await admin.from("organizations").select("status").eq("id",organizationId).maybeSingle();return Boolean(data&&data.status!=="archived");}
const all=(form:FormData,key:string)=>form.getAll(key).map(String);

export async function createPlatformSchool(formData:FormData){
  const user=await platformUser(), value=(key:string)=>String(formData.get(key)||"").trim();
  const school=schoolSchema.safeParse({name:value("name"),slug:value("slug"),legal_name:value("legal_name"),website_url:value("website_url"),school_type:value("school_type"),education_board:value("education_board"),established_year:value("established_year"),affiliation_number:value("affiliation_number"),primary_email:value("primary_email"),primary_phone:value("primary_phone"),plan_name:value("plan_name"),customer_success_owner:value("customer_success_owner"),billing_cycle:value("billing_cycle"),recurring_amount:value("recurring_amount"),implementation_fee:value("implementation_fee"),contract_status:value("contract_status"),contract_starts_on:value("contract_starts_on"),contract_ends_on:value("contract_ends_on"),licensed_students:value("licensed_students")});
  const names=all(formData,"branch_name"),codes=all(formData,"branch_code"),addresses=all(formData,"branch_address"),cities=all(formData,"branch_city"),states=all(formData,"branch_state"),postals=all(formData,"branch_postal"),lats=all(formData,"branch_latitude"),lngs=all(formData,"branch_longitude"),branchEmails=all(formData,"branch_email"),branchPhones=all(formData,"branch_phone");
  const branches=z.array(branchSchema).min(1).max(50).safeParse(names.map((name,i)=>({name,code:codes[i],address_line1:addresses[i],city:cities[i],state:states[i],postal_code:postals[i],latitude:lats[i],longitude:lngs[i],email:branchEmails[i],phone:branchPhones[i]})));
  const ownerNames=all(formData,"owner_name"),ownerEmails=all(formData,"owner_email"),ownerPhones=all(formData,"owner_phone"),ownerTitles=all(formData,"owner_title");
  const owners=z.array(ownerSchema).min(1).max(20).safeParse(ownerNames.map((name,i)=>({name,email:ownerEmails[i],phone:ownerPhones[i],job_title:ownerTitles[i]})));
  if(!school.success||!branches.success||!owners.success||new Set(branches.success?branches.data.map(b=>b.code.toUpperCase()):[]).size!==names.length||new Set(owners.success?owners.data.map(o=>o.email):[]).size!==ownerNames.length)status("error","Review the school, branch, owner, and commercial details. Branch codes and owner emails must be unique.","onboarding");
  const website=school.data.website_url?normalizedWebsiteUrl(school.data.website_url):"";if(school.data.website_url&&!website)status("error","Enter a valid school website address.","onboarding");
  const admin=createAdminClient(),env=getPublicEnv();if(!admin||!env)status("error","Trusted provisioning is not configured.","onboarding");
  const createdUserIds:string[]=[];let logoPath="",logoUrl="",invitationCount=0;
  try{
    const invited=[];
    for(const [index,entry] of owners.data.entries()){
      const account=await findOrInviteAuthUser(admin,{email:entry.email,fullName:entry.name,redirectTo:`${env.NEXT_PUBLIC_APP_URL}/auth/complete`});
      if(account.created)createdUserIds.push(account.user.id);if(account.invitationSent)invitationCount++;
      invited.push({user_id:account.user.id,job_title:entry.job_title,phone:entry.phone,is_primary:index===0});
    }
    const logo=formData.get("logo");
    if(logo instanceof File&&logo.size){
      if(logo.size>2097152||!["image/png","image/jpeg","image/webp"].includes(logo.type))throw new Error("INVALID_LOGO");
      const extension=logo.type==="image/png"?"png":logo.type==="image/webp"?"webp":"jpg";logoPath=`${school.data.slug}/${crypto.randomUUID()}.${extension}`;
      const upload=await admin.storage.from("brand-assets").upload(logoPath,Buffer.from(await logo.arrayBuffer()),{contentType:logo.type,upsert:false});if(upload.error)throw upload.error;
      logoUrl=admin.storage.from("brand-assets").getPublicUrl(logoPath).data.publicUrl;
    }
    const {error}=await admin.rpc("platform_create_school_portfolio",{p_name:school.data.name,p_slug:school.data.slug.toLowerCase(),p_legal_name:school.data.legal_name||"",p_website_url:website,p_logo_url:logoUrl,p_school_type:school.data.school_type,p_education_board:school.data.education_board||"",p_established_year:school.data.established_year||null,p_affiliation_number:school.data.affiliation_number||"",p_primary_email:school.data.primary_email||"",p_primary_phone:school.data.primary_phone||"",p_customer_success_owner:school.data.customer_success_owner||"",p_branches:branches.data.map(b=>({...b,code:b.code.toUpperCase(),country:"India"})),p_owners:invited,p_plan_name:school.data.plan_name,p_billing_cycle:school.data.billing_cycle,p_recurring_amount:school.data.recurring_amount,p_implementation_fee:school.data.implementation_fee,p_contract_status:school.data.contract_status,p_contract_starts_on:school.data.contract_starts_on||null,p_contract_ends_on:school.data.contract_ends_on||null,p_licensed_students:school.data.licensed_students||null,p_actor_user:user.id});if(error)throw error;
  }catch(error){
    if(logoPath)await admin.storage.from("brand-assets").remove([logoPath]);for(const id of createdUserIds)await admin.auth.admin.deleteUser(id);
    const code=typeof error==="object"&&error!==null&&"code" in error?error.code:"";const message=error instanceof Error&&error.message==="INVALID_LOGO"?"Use a PNG, JPEG, or WebP logo no larger than 2 MB.":code==="23505"?"That school URL, branch code, or owner assignment is already in use.":"The portfolio could not be provisioned. No partial school record was kept.";status("error",message,"onboarding");
  }
  revalidatePath("/platform");status("success",`${school.data.name} is ready with ${branches.data.length} branch${branches.data.length===1?"":"es"}; ${invitationCount} owner invitation${invitationCount===1?" was":"s were"} sent.`,"onboarding");
}

export async function resendOwnerInvitation(formData:FormData){
  await platformUser();const organizationId=String(formData.get("organization_id")||""),userId=String(formData.get("user_id")||""),returnView=String(formData.get("return_view")||"owners");if(!z.string().uuid().safeParse(organizationId).success||!z.string().uuid().safeParse(userId).success)status("error","Choose a valid school owner.",returnView);
  const admin=createAdminClient(),env=getPublicEnv();if(!admin||!env)status("error","Trusted provisioning is not configured.");if(!await schoolCanBeChanged(admin,organizationId))status("error","Restore this school before inviting owners.");const {data:membership}=await admin.from("memberships").select("user_id").eq("organization_id",organizationId).eq("user_id",userId).eq("role","owner").eq("status","active").maybeSingle();if(!membership)status("error","That owner does not have active access to this school.");
  const {data,error}=await admin.auth.admin.getUserById(userId);if(error||!data.user?.email)status("error","The owner account could not be loaded.",returnView);if(data.user.email_confirmed_at)status("success",`${data.user.email} has already activated their account.`,returnView);const result=await admin.auth.admin.inviteUserByEmail(data.user.email,{data:data.user.user_metadata,redirectTo:`${env.NEXT_PUBLIC_APP_URL}/auth/complete`});if(result.error)status("error","A fresh invitation could not be sent. Wait one minute and retry.",returnView);status("success",`A fresh owner invitation was sent to ${data.user.email}.`,returnView);
}

export async function updatePlatformSchool(formData:FormData){
  const user=await platformUser(),organizationId=String(formData.get("organization_id")||"");if(!z.string().uuid().safeParse(organizationId).success)status("error","Choose a valid school.");const value=(key:string)=>String(formData.get(key)||"").trim();
  const parsed=schoolSchema.safeParse({name:"Existing school",slug:"existing-school",legal_name:"",website_url:value("website_url"),school_type:value("school_type"),education_board:value("education_board"),established_year:value("established_year"),affiliation_number:value("affiliation_number"),primary_email:value("primary_email"),primary_phone:value("primary_phone"),plan_name:value("plan_name"),customer_success_owner:value("customer_success_owner"),billing_cycle:value("billing_cycle"),recurring_amount:value("recurring_amount"),implementation_fee:value("implementation_fee"),contract_status:value("contract_status"),contract_starts_on:value("contract_starts_on"),contract_ends_on:value("contract_ends_on"),licensed_students:value("licensed_students")});
  const stage=z.enum(["invited","profile","data_import","training","live","paused"]).safeParse(value("onboarding_stage")),goLive=z.preprocess(emptyToUndefined,z.string().date().optional()).safeParse(value("go_live_on"));if(!parsed.success||!stage.success||!goLive.success)schoolStatus(organizationId,"error","Review the school profile and commercial details.");const website=parsed.data.website_url?normalizedWebsiteUrl(parsed.data.website_url):"";if(parsed.data.website_url&&!website)schoolStatus(organizationId,"error","Enter a valid school website address.");
  const admin=createAdminClient();if(!admin)schoolStatus(organizationId,"error","Trusted provisioning is not configured.");if(!await schoolCanBeChanged(admin,organizationId))status("error","Restore this school before changing its portfolio.");let logoPath="",logoUrl="";
  try{const logo=formData.get("logo");if(logo instanceof File&&logo.size){if(logo.size>2097152||!["image/png","image/jpeg","image/webp"].includes(logo.type))throw new Error("INVALID_LOGO");const extension=logo.type==="image/png"?"png":logo.type==="image/webp"?"webp":"jpg";logoPath=`${organizationId}/${crypto.randomUUID()}.${extension}`;const upload=await admin.storage.from("brand-assets").upload(logoPath,Buffer.from(await logo.arrayBuffer()),{contentType:logo.type,upsert:false});if(upload.error)throw upload.error;logoUrl=admin.storage.from("brand-assets").getPublicUrl(logoPath).data.publicUrl;}
    const {error}=await admin.rpc("platform_update_school_portfolio",{p_org:organizationId,p_website_url:website,p_logo_url:logoUrl,p_school_type:parsed.data.school_type,p_education_board:parsed.data.education_board||"",p_established_year:parsed.data.established_year||null,p_affiliation_number:parsed.data.affiliation_number||"",p_primary_email:parsed.data.primary_email||"",p_primary_phone:parsed.data.primary_phone||"",p_onboarding_stage:stage.data,p_go_live_on:goLive.data||null,p_customer_success_owner:parsed.data.customer_success_owner||"",p_plan_name:parsed.data.plan_name,p_billing_cycle:parsed.data.billing_cycle,p_recurring_amount:parsed.data.recurring_amount,p_implementation_fee:parsed.data.implementation_fee,p_contract_status:parsed.data.contract_status,p_contract_starts_on:parsed.data.contract_starts_on||null,p_contract_ends_on:parsed.data.contract_ends_on||null,p_licensed_students:parsed.data.licensed_students||null,p_actor_user:user.id});if(error)throw error;
  }catch(error){if(logoPath)await admin.storage.from("brand-assets").remove([logoPath]);schoolStatus(organizationId,"error",error instanceof Error&&error.message==="INVALID_LOGO"?"Use a PNG, JPEG, or WebP logo no larger than 2 MB.":"The school portfolio could not be updated.");}
  revalidatePath("/platform");revalidatePath(`/platform/schools/${organizationId}`);schoolStatus(organizationId,"success","School profile and commercial details updated.",String(formData.get("return_view")||"school"));
}

export async function addPlatformBranches(formData:FormData){
  const user=await platformUser(),organizationId=String(formData.get("organization_id")||"");if(!z.string().uuid().safeParse(organizationId).success)status("error","Choose a valid school.");const names=all(formData,"new_branch_name"),codes=all(formData,"new_branch_code"),addresses=all(formData,"new_branch_address"),cities=all(formData,"new_branch_city"),states=all(formData,"new_branch_state"),postals=all(formData,"new_branch_postal"),lats=all(formData,"new_branch_latitude"),lngs=all(formData,"new_branch_longitude"),emails=all(formData,"new_branch_email"),phones=all(formData,"new_branch_phone");const parsed=z.array(branchSchema).min(1).max(50).safeParse(names.map((name,i)=>({name,code:codes[i],address_line1:addresses[i],city:cities[i],state:states[i],postal_code:postals[i],latitude:lats[i],longitude:lngs[i],email:emails[i],phone:phones[i]})));if(!parsed.success||new Set(parsed.success?parsed.data.map(b=>b.code.toUpperCase()):[]).size!==names.length)schoolStatus(organizationId,"error","Review the new branches and use unique branch codes.");const admin=createAdminClient();if(!admin)schoolStatus(organizationId,"error","Trusted provisioning is not configured.");if(!await schoolCanBeChanged(admin,organizationId))status("error","Restore this school before adding branches.");const {data,error}=await admin.rpc("platform_add_school_branches",{p_org:organizationId,p_branches:parsed.data.map(b=>({...b,code:b.code.toUpperCase(),country:"India"})),p_actor_user:user.id});if(error)schoolStatus(organizationId,"error",error.code==="23505"?"A branch code already exists in this school.":"The branches could not be added.");revalidatePath("/platform");revalidatePath(`/platform/schools/${organizationId}`);schoolStatus(organizationId,"success",`${data} branch${data===1?"":"es"} added.`,String(formData.get("return_view")||"branches"));
}

export async function updatePlatformBranch(formData:FormData){
  const user=await platformUser(),organizationId=String(formData.get("organization_id")||""),branchId=String(formData.get("branch_id")||"");if(!z.string().uuid().safeParse(organizationId).success||!z.string().uuid().safeParse(branchId).success)status("error","Choose a valid branch.");const parsed=branchSchema.safeParse({name:"Existing branch",code:"EX",address_line1:formData.get("address_line1"),city:formData.get("city"),state:formData.get("state"),postal_code:formData.get("postal_code"),latitude:formData.get("latitude"),longitude:formData.get("longitude"),email:formData.get("email"),phone:formData.get("phone")});if(!parsed.success)schoolStatus(organizationId,"error","Review the branch address and coordinates.");const admin=createAdminClient();if(!admin)schoolStatus(organizationId,"error","Trusted provisioning is not configured.");if(!await schoolCanBeChanged(admin,organizationId))status("error","Restore this school before changing a branch.");const {error}=await admin.rpc("platform_update_school_branch",{p_org:organizationId,p_branch:branchId,p_address_line1:parsed.data.address_line1,p_city:parsed.data.city,p_state:parsed.data.state,p_postal_code:parsed.data.postal_code,p_latitude:parsed.data.latitude||null,p_longitude:parsed.data.longitude||null,p_email:parsed.data.email||"",p_phone:parsed.data.phone,p_actor_user:user.id});if(error)schoolStatus(organizationId,"error","The branch location could not be updated.");revalidatePath(`/platform/schools/${organizationId}`);schoolStatus(organizationId,"success","Branch location updated.",String(formData.get("return_view")||"branches"));
}

export async function invitePlatformOwners(formData:FormData){
  const user=await platformUser(),organizationId=String(formData.get("organization_id")||"");if(!z.string().uuid().safeParse(organizationId).success)status("error","Choose a valid school.");const names=all(formData,"new_owner_name"),emails=all(formData,"new_owner_email"),phones=all(formData,"new_owner_phone"),titles=all(formData,"new_owner_title");const parsed=z.array(ownerSchema).min(1).max(20).safeParse(names.map((name,i)=>({name,email:emails[i],phone:phones[i],job_title:titles[i]})));if(!parsed.success||new Set(parsed.success?parsed.data.map(o=>o.email):[]).size!==names.length)schoolStatus(organizationId,"error","Review the owner details and use unique email addresses.");const admin=createAdminClient(),env=getPublicEnv();if(!admin||!env)schoolStatus(organizationId,"error","Trusted provisioning is not configured.");if(!await schoolCanBeChanged(admin,organizationId))status("error","Restore this school before inviting owners.");const createdIds:string[]=[];let invitedCount=0;try{const owners=[];for(const entry of parsed.data){const account=await findOrInviteAuthUser(admin,{email:entry.email,fullName:entry.name,redirectTo:`${env.NEXT_PUBLIC_APP_URL}/auth/complete`});if(account.created)createdIds.push(account.user.id);if(account.invitationSent)invitedCount++;owners.push({user_id:account.user.id,job_title:entry.job_title,phone:entry.phone,is_primary:false});}const {error}=await admin.rpc("platform_add_school_owners",{p_org:organizationId,p_owners:owners,p_actor_user:user.id});if(error)throw error;}catch{for(const id of createdIds)await admin.auth.admin.deleteUser(id);schoolStatus(organizationId,"error","The owners could not be added. No new access was retained.");}revalidatePath("/platform");revalidatePath(`/platform/schools/${organizationId}`);schoolStatus(organizationId,"success",`${parsed.data.length} owner${parsed.data.length===1?"":"s"} added; ${invitedCount} invitation${invitedCount===1?" was":"s were"} sent.`,String(formData.get("return_view")||"owners"));
}

export async function setPlatformSchoolArchived(formData:FormData){
  const user=await platformUser(),organizationId=String(formData.get("organization_id")||""),archived=String(formData.get("archived"))==="true",reason=String(formData.get("reason")||"").trim();
  if(!z.string().uuid().safeParse(organizationId).success)status("error","Choose a valid school.");
  const admin=createAdminClient();if(!admin)status("error","Trusted provisioning is not configured.");
  if(archived){
    const schoolName=String(formData.get("school_name")||""),confirmation=String(formData.get("confirmation")||"");
    const {data:school}=await admin.from("organizations").select("name,status").eq("id",organizationId).maybeSingle();
    if(!school||school.status==="archived")status("error","That school is already unavailable.");
    if(schoolName!==school.name||confirmation!==school.name)schoolStatus(organizationId,"error",`Type ${school.name} exactly to confirm deletion.`);
  }
  const {error}=await admin.rpc("platform_set_school_archived",{p_org:organizationId,p_archived:archived,p_reason:reason,p_actor_user:user.id});
  if(error)status("error",archived?"The school could not be deleted safely.":"The school could not be restored.");
  revalidatePath("/platform");revalidatePath(`/platform/schools/${organizationId}`);
  status("success",archived?"School deleted from the active portfolio. Records were retained for audit and recovery.":"School restored with its previous access and onboarding stage.");
}
