import Link from "next/link";
import { redirect } from "next/navigation";
import { logout } from "@/app/login/actions";
import { isPlatformOwnerEmail } from "@/lib/auth/platform";
import { annualizeRecurringRevenue, countByOrganization } from "@/lib/platform/portfolio";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { resendOwnerInvitation } from "./actions";
import { SchoolPortfolioForm } from "./school-form";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
export default async function PlatformPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
  const supabase=await createClient();const {data:{user}}=supabase?await supabase.auth.getUser():{data:{user:null}};if(!user)redirect("/login?next=/platform");if(!isPlatformOwnerEmail(user.email))redirect("/dashboard");
  const admin=createAdminClient();if(!admin)throw new Error("Platform administration is not configured.");
  const [orgsResult,campusesResult,membersResult,studentsResult,staffResult,commercialsResult,ownerProfilesResult,usersResult]=await Promise.all([
    admin.from("organizations").select("id,name,slug,status,website_url,logo_url,school_type,education_board,onboarding_stage,created_at").order("created_at",{ascending:false}),
    admin.from("campuses").select("id,organization_id"),admin.from("memberships").select("id,organization_id,user_id,role,status"),
    admin.from("students").select("organization_id").eq("status","active"),admin.from("staff_profiles").select("organization_id,designation").eq("status","active"),
    admin.from("organization_commercials").select("organization_id,plan_name,billing_cycle,recurring_amount,contract_status,licensed_students"),
    admin.from("organization_owner_profiles").select("organization_id,user_id,phone,job_title,is_primary"),admin.auth.admin.listUsers({page:1,perPage:1000}),
  ]);
  if(orgsResult.error||campusesResult.error||membersResult.error||studentsResult.error||staffResult.error||commercialsResult.error||ownerProfilesResult.error||usersResult.error)throw new Error("The school portfolio could not be loaded.");
  const organizations=orgsResult.data||[],campuses=campusesResult.data||[],members=membersResult.data||[],students=studentsResult.data||[],staff=staffResult.data||[],commercials=commercialsResult.data||[],ownerProfiles=ownerProfilesResult.data||[];
  const users=new Map((usersResult.data.users||[]).map(item=>[item.id,item])),branchCounts=countByOrganization(campuses),studentCounts=countByOrganization(students),staffCounts=countByOrganization(staff),teacherCounts=countByOrganization(staff.filter(item=>/teacher|faculty|educator/i.test(item.designation))),ownerMemberships=members.filter(item=>item.role==="owner"&&item.status==="active"),ownerProfileMap=new Map(ownerProfiles.map(item=>[`${item.organization_id}:${item.user_id}`,item]));
  const commercialsByOrg=new Map(commercials.map(item=>[item.organization_id,item]));const arr=commercials.filter(item=>item.contract_status==="active").reduce((total,item)=>total+annualizeRecurringRevenue(Number(item.recurring_amount),item.billing_cycle as "monthly"|"quarterly"|"annual"),0);
  const query=await searchParams,activeSchools=organizations.filter(item=>item.status==="active").length,liveSchools=organizations.filter(item=>item.onboarding_stage==="live").length;
  return <main className="platform-page"><header className="platform-topbar"><Link className="brand" href="/platform"><span className="brand-mark"><i/><i/><i/></span><span>Northstar Platform</span></Link><div><Link className="secondary compact" href="/dashboard/access">Access guide</Link><Link className="secondary compact" href="/dashboard">Open my school</Link><form action={logout}><button className="signout">Sign out</button></form></div></header><div className="platform-content">
    <div className="page-head"><div><span className="eyebrow">PLATFORM PORTFOLIO</span><h1>Every school, owner and renewal.</h1><p>Provision tenants, track onboarding, and see live adoption and commercial health across the network.</p></div><span className="status">SERVICE ADMIN ONLY</span></div>
    {(query.success||query.error)&&<p className={query.error?"form-error admin-message":"form-success admin-message"} role="status">{query.error||query.success}</p>}
    <section className="platform-metrics"><article><span>Schools</span><strong>{activeSchools}</strong><small>{liveSchools} live</small></article><article><span>Branches</span><strong>{campuses.length}</strong><small>Across all tenants</small></article><article><span>Students</span><strong>{students.length}</strong><small>{staff.length} staff · {staff.filter(item=>/teacher|faculty|educator/i.test(item.designation)).length} teachers</small></article><article><span>ARR</span><strong>{money.format(arr)}</strong><small>Active contracts, annualized</small></article></section>
    <div className="portfolio-layout"><section className="card"><header className="card-header"><div><h2>School portfolio</h2><p>Live operational and commercial totals by tenant.</p></div><span className="status">{organizations.length} records</span></header><div className="portfolio-table" role="table" aria-label="School portfolio"><div className="portfolio-row portfolio-heading" role="row"><span>School</span><span>Footprint</span><span>People</span><span>Contract</span><span>Status</span></div>{organizations.map(school=>{const commercial=commercialsByOrg.get(school.id),schoolArr=commercial?annualizeRecurringRevenue(Number(commercial.recurring_amount),commercial.billing_cycle as "monthly"|"quarterly"|"annual"):0;return <Link href={`/platform/schools/${school.id}`} className="portfolio-row" role="row" key={school.id}><span className="school-cell">{school.logo_url?<i className="logo-thumb" style={{backgroundImage:`url(${school.logo_url})`}}/>:<i>{school.name.slice(0,2).toUpperCase()}</i>}<span><b>{school.name}</b><small>{school.education_board||school.school_type.replaceAll("_"," ")}{school.website_url?" · website added":""}</small></span></span><span><b>{branchCounts.get(school.id)||0} branches</b><small>{commercial?.licensed_students?`${commercial.licensed_students} licensed students`:"No licence cap"}</small></span><span><b>{studentCounts.get(school.id)||0} students</b><small>{staffCounts.get(school.id)||0} staff · {teacherCounts.get(school.id)||0} teachers</small></span><span><b>{money.format(schoolArr)}</b><small>{commercial?.plan_name||"Commercials pending"}</small></span><span><span className={`status ${school.onboarding_stage==="live"?"":"status-warning"}`}>{school.onboarding_stage.replaceAll("_"," ")}</span><small>View details →</small></span></Link>})}{!organizations.length&&<p className="empty-copy task-empty">No school tenants yet.</p>}</div></section>
      <aside className="card create-school-card"><header className="card-header"><div><h2>Add school portfolio</h2><p>Create all branches and invite multiple owners in one controlled workflow.</p></div></header><details open><summary>Open onboarding form</summary><SchoolPortfolioForm/></details></aside></div>
    <section className="card owner-directory"><header className="card-header"><div><h2>School owner directory</h2><p>Primary contacts, tenant scope, and activation state.</p></div><span className="status">{ownerMemberships.length} OWNERS</span></header><div className="owner-table"><div className="owner-row owner-heading"><span>Owner</span><span>School</span><span>Contact</span><span>Responsibility</span><span>Access</span></div>{ownerMemberships.map(membership=>{const profile=ownerProfileMap.get(`${membership.organization_id}:${membership.user_id}`),authUser=users.get(membership.user_id),school=organizations.find(item=>item.id===membership.organization_id);return <div className="owner-row" key={membership.id}><span><b>{String(authUser?.user_metadata?.full_name||authUser?.email?.split("@")[0]||"Owner")}</b><small>{authUser?.email||"Email unavailable"}</small></span><span><b>{school?.name||"School"}</b><small>{profile?.is_primary!==false?"Primary owner":"Additional owner"}</small></span><span><b>{profile?.phone||"—"}</b><small>{authUser?.email||""}</small></span><span><b>{profile?.job_title||"School owner"}</b><small>Tenant-wide</small></span><span>{authUser?.email_confirmed_at?<span className="status">Active</span>:<form action={resendOwnerInvitation}><input type="hidden" name="organization_id" value={membership.organization_id}/><input type="hidden" name="user_id" value={membership.user_id}/><button className="secondary compact">Resend invite</button></form>}</span></div>})}{!ownerMemberships.length&&<p className="empty-copy task-empty">No school owners have been assigned.</p>}</div></section>
  </div></main>;
}
