import Link from "next/link";
import { redirect } from "next/navigation";
import { logout } from "@/app/login/actions";
import { isPlatformOwnerEmail } from "@/lib/auth/platform";
import { annualizeRecurringRevenue, countByOrganization, forecastedAnnualRevenue, pilotState } from "@/lib/platform/portfolio";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { resendOwnerInvitation } from "./actions";
import { SchoolPortfolioForm } from "./school-form";
import { RestoreSchoolForm } from "./schools/[id]/archive-school-form";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const tabs = [["schools", "School portfolio"], ["branches", "Branches"], ["owners", "Owners"], ["commercials", "Commercials"], ["onboarding", "Onboarding"]] as const;

export default async function PlatformPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string; view?: string }> }) {
  const supabase = await createClient();
  const { data: { user } } = supabase ? await supabase.auth.getUser() : { data: { user: null } };
  if (!user) redirect("/login?next=/platform");
  if (!isPlatformOwnerEmail(user.email)) redirect("/dashboard");
  const admin = createAdminClient();
  if (!admin) throw new Error("Platform administration is not configured.");
  const [orgsResult, campusesResult, membersResult, studentsResult, staffResult, commercialsResult, ownerProfilesResult, usersResult] = await Promise.all([
    admin.from("organizations").select("id,name,slug,status,website_url,logo_url,school_type,education_board,onboarding_stage,created_at").order("created_at", { ascending: false }),
    admin.from("campuses").select("id,organization_id,name,code,address_line1,city,state,postal_code,email,phone,status").order("name"),
    admin.from("memberships").select("id,organization_id,user_id,role,status"),
    admin.from("students").select("organization_id").eq("status", "active"),
    admin.from("staff_profiles").select("organization_id,designation").eq("status", "active"),
    admin.from("organization_commercials").select("organization_id,plan_name,billing_cycle,recurring_amount,contract_status,contract_starts_on,contract_ends_on,licensed_students"),
    admin.from("organization_owner_profiles").select("organization_id,user_id,phone,job_title,is_primary"),
    admin.auth.admin.listUsers({ page: 1, perPage: 1000 }),
  ]);
  if (orgsResult.error || campusesResult.error || membersResult.error || studentsResult.error || staffResult.error || commercialsResult.error || ownerProfilesResult.error || usersResult.error) throw new Error("The school portfolio could not be loaded.");
  const organizations = orgsResult.data || [], campuses = campusesResult.data || [], members = membersResult.data || [], students = studentsResult.data || [], staff = staffResult.data || [], commercials = commercialsResult.data || [], ownerProfiles = ownerProfilesResult.data || [];
  const users = new Map((usersResult.data.users || []).map(item => [item.id, item]));
  const branchCounts = countByOrganization(campuses), studentCounts = countByOrganization(students), staffCounts = countByOrganization(staff), teacherCounts = countByOrganization(staff.filter(item => /teacher|faculty|educator/i.test(item.designation)));
  const ownerProfileMap = new Map(ownerProfiles.map(item => [`${item.organization_id}:${item.user_id}`, item]));
  const commercialsByOrg = new Map(commercials.map(item => [item.organization_id, item]));
  const activeOrganizations = organizations.filter(item => item.status !== "archived"), archivedOrganizations = organizations.filter(item => item.status === "archived");
  const activeIds = new Set(activeOrganizations.map(item => item.id)), activeCommercials = commercials.filter(item => activeIds.has(item.organization_id));
  const organizationsById = new Map(organizations.map(item => [item.id, item]));
  const ownerMemberships = members.filter(item => item.role === "owner" && item.status === "active" && activeIds.has(item.organization_id));
  const activeCampuses = campuses.filter(item => activeIds.has(item.organization_id));
  const arr = activeCommercials.filter(item => item.contract_status === "active").reduce((total, item) => total + annualizeRecurringRevenue(Number(item.recurring_amount), item.billing_cycle as "monthly" | "quarterly" | "annual"), 0);
  const forecastArr = forecastedAnnualRevenue(activeOrganizations.length), activePilots = activeCommercials.filter(item => pilotState(item.contract_status, item.contract_ends_on) === "active"), expiredPilots = activeCommercials.filter(item => pilotState(item.contract_status, item.contract_ends_on) === "expired");
  const query = await searchParams, requestedView = query.view === "pipeline" || query.view === "pilots" ? "onboarding" : query.view;
  const view = tabs.some(([key]) => key === requestedView) ? requestedView : "schools";
  const activeSchools = activeOrganizations.filter(item => item.status === "active").length, liveSchools = activeOrganizations.filter(item => item.onboarding_stage === "live").length;
  const activeStudents = students.filter(item => activeIds.has(item.organization_id)), activeStaff = staff.filter(item => activeIds.has(item.organization_id));
  const pipelineSchools = activeOrganizations.filter(item => item.onboarding_stage !== "live"), pilotCommercials = activeCommercials.filter(item => item.contract_status === "trial");

  return <main className="platform-page"><header className="platform-topbar"><Link className="brand" href="/platform"><span className="brand-mark"><i /><i /><i /></span><span>Northstar Platform</span></Link><div><Link className="secondary compact" href="/dashboard/access">Access guide</Link><Link className="secondary compact" href="/dashboard">Open my school</Link><form action={logout}><button className="signout">Sign out</button></form></div></header><div className="platform-content">
    <div className="page-head"><div><span className="eyebrow">PLATFORM PORTFOLIO</span><h1>Every school, owner and renewal.</h1><p>Provision tenants, track onboarding, and see live adoption and commercial health across the network.</p></div><span className="status">SERVICE ADMIN ONLY</span></div>
    {(query.success || query.error) && <p className={query.error ? "form-error admin-message" : "form-success admin-message"} role="status">{query.error || query.success}</p>}
    <section className="platform-metrics portfolio-kpis"><article><span>Schools</span><strong>{activeSchools}</strong><small>{liveSchools} live · {archivedOrganizations.length} deleted</small></article><article><span>Piloted schools</span><strong>{activePilots.length}</strong><small>1 month free · {expiredPilots.length} expired</small></article><article><span>Branches</span><strong>{activeCampuses.length}</strong><small>Across active tenants</small></article><article><span>Students</span><strong>{activeStudents.length}</strong><small>{activeStaff.length} staff · {activeStaff.filter(item => /teacher|faculty|educator/i.test(item.designation)).length} teachers</small></article><article><span>Current ARR</span><strong>{money.format(arr)}</strong><small>Active contracts, annualized</small></article><article><span>Forecast ARR</span><strong>{money.format(forecastArr)}</strong><small>₹3,00,000 per non-deleted school</small></article></section>
    <nav className="platform-tabs portfolio-main-tabs" aria-label="Platform portfolio sections">{tabs.map(([key, label]) => <Link key={key} href={`/platform?view=${key}`} aria-current={view === key ? "page" : undefined} className={view === key ? "active" : ""}>{label}</Link>)}</nav>

    {view === "schools" && <div className="platform-tab-stack">
      <section className="card school-brands"><header className="card-header"><div><h2>School brands</h2><p>Logo-led portfolio view across every non-deleted tenant.</p></div><span className="status">{activeOrganizations.length} SCHOOLS</span></header><div className="brand-grid">{activeOrganizations.map(school => <Link href={`/platform/schools/${school.id}`} key={school.id}>{school.logo_url ? <i className="portfolio-logo" style={{ backgroundImage: `url(${school.logo_url})` }} /> : <i className="portfolio-logo portfolio-initials">{school.name.slice(0, 2).toUpperCase()}</i>}<span><b>{school.name}</b><small>{branchCounts.get(school.id) || 0} branches · {studentCounts.get(school.id) || 0} students</small></span></Link>)}</div></section>
      <section className="card tab-panel"><header className="card-header"><div><h2>School portfolio</h2><p>Live operational and commercial totals by tenant.</p></div><span className="status">{activeOrganizations.length} ACTIVE</span></header><div className="portfolio-table" role="table" aria-label="School portfolio"><div className="portfolio-row portfolio-heading" role="row"><span>School</span><span>Footprint</span><span>People</span><span>Contract</span><span>Status</span></div>{activeOrganizations.map(school => { const commercial = commercialsByOrg.get(school.id), schoolArr = commercial ? annualizeRecurringRevenue(Number(commercial.recurring_amount), commercial.billing_cycle as "monthly" | "quarterly" | "annual") : 0, pilot = pilotState(commercial?.contract_status || "", commercial?.contract_ends_on || null); return <Link href={`/platform/schools/${school.id}`} className="portfolio-row" role="row" key={school.id}><span className="school-cell">{school.logo_url ? <i className="logo-thumb" style={{ backgroundImage: `url(${school.logo_url})` }} /> : <i>{school.name.slice(0, 2).toUpperCase()}</i>}<span><b>{school.name}</b><small>{school.education_board || school.school_type.replaceAll("_", " ")}{school.website_url ? " · website added" : ""}</small></span></span><span><b>{branchCounts.get(school.id) || 0} branches</b><small>{commercial?.licensed_students ? `${commercial.licensed_students} licensed students` : "No licence cap"}</small></span><span><b>{studentCounts.get(school.id) || 0} students</b><small>{staffCounts.get(school.id) || 0} staff · {teacherCounts.get(school.id) || 0} teachers</small></span><span><b>{money.format(schoolArr)}</b><small>{pilot === "active" ? `Pilot until ${commercial?.contract_ends_on}` : commercial?.plan_name || "Commercials pending"}</small></span><span><span className={`status ${school.onboarding_stage === "live" ? "" : "status-warning"}`}>{school.onboarding_stage.replaceAll("_", " ")}</span><small>View details →</small></span></Link>; })}{!activeOrganizations.length && <p className="empty-copy task-empty">No active school tenants yet.</p>}</div></section>
      {archivedOrganizations.length > 0 && <section className="card archived-schools"><header className="card-header"><div><h2>Deleted schools</h2><p>Access is disabled. Restore a school without losing retained records.</p></div><span className="status status-warning">{archivedOrganizations.length}</span></header><div>{archivedOrganizations.map(school => <article key={school.id}><span className="school-cell">{school.logo_url ? <i className="logo-thumb" style={{ backgroundImage: `url(${school.logo_url})` }} /> : <i>{school.name.slice(0, 2).toUpperCase()}</i>}<span><b>{school.name}</b><small>{school.slug}</small></span></span><RestoreSchoolForm organizationId={school.id} /></article>)}</div></section>}
    </div>}

    {view === "branches" && <section className="card tab-panel"><header className="card-header"><div><h2>Branch directory</h2><p>Every active campus, its school, location and contact details.</p></div><span className="status">{activeCampuses.length} BRANCHES</span></header><div className="branch-directory" role="table" aria-label="Branch directory"><div className="branch-directory-row branch-directory-heading" role="row"><span>Branch</span><span>School</span><span>Location</span><span>Contact</span><span>Status</span></div>{activeCampuses.map(branch => { const school = organizationsById.get(branch.organization_id); return <Link href={`/platform/schools/${branch.organization_id}?view=branches`} className="branch-directory-row" role="row" key={branch.id}><span><b>{branch.name}</b><small>{branch.code}</small></span><span><b>{school?.name || "School"}</b><small>Open branch management →</small></span><span><b>{[branch.city, branch.state].filter(Boolean).join(", ") || "Location pending"}</b><small>{[branch.address_line1, branch.postal_code].filter(Boolean).join(" · ") || "Address incomplete"}</small></span><span><b>{branch.email || "—"}</b><small>{branch.phone || "No phone"}</small></span><span className={`status ${branch.status === "active" ? "" : "status-warning"}`}>{branch.status}</span></Link>; })}{!activeCampuses.length && <p className="empty-copy task-empty">No branches have been added.</p>}</div></section>}

    {view === "owners" && <section className="card tab-panel"><header className="card-header"><div><h2>School owner directory</h2><p>Primary contacts, tenant scope, and activation state.</p></div><span className="status">{ownerMemberships.length} OWNERS</span></header><div className="owner-table"><div className="owner-row owner-heading"><span>Owner</span><span>School</span><span>Contact</span><span>Responsibility</span><span>Access</span></div>{ownerMemberships.map(membership => { const profile = ownerProfileMap.get(`${membership.organization_id}:${membership.user_id}`), authUser = users.get(membership.user_id), school = organizationsById.get(membership.organization_id); return <div className="owner-row" key={membership.id}><span><b>{String(authUser?.user_metadata?.full_name || authUser?.email?.split("@")[0] || "Owner")}</b><small>{authUser?.email || "Email unavailable"}</small></span><span><Link href={`/platform/schools/${membership.organization_id}?view=owners`}><b>{school?.name || "School"}</b></Link><small>{profile?.is_primary !== false ? "Primary owner" : "Additional owner"}</small></span><span><b>{profile?.phone || "—"}</b><small>{authUser?.email || ""}</small></span><span><b>{profile?.job_title || "School owner"}</b><small>Tenant-wide</small></span><span>{authUser?.email_confirmed_at ? <span className="status">Active</span> : <form action={resendOwnerInvitation}><input type="hidden" name="organization_id" value={membership.organization_id} /><input type="hidden" name="user_id" value={membership.user_id} /><input type="hidden" name="return_view" value="owners" /><button className="secondary compact">Resend invite</button></form>}</span></div>; })}{!ownerMemberships.length && <p className="empty-copy task-empty">No school owners have been assigned.</p>}</div></section>}

    {view === "commercials" && <section className="card tab-panel"><header className="card-header"><div><h2>Commercials</h2><p>Contracted revenue, fixed-price forecast, plan and renewal term by school.</p></div><span className="status">{activeOrganizations.length} ACCOUNTS</span></header><div className="commercial-table"><div className="commercial-row commercial-heading"><span>School</span><span>Plan</span><span>Current ARR</span><span>Forecast ARR</span><span>Term</span></div>{activeOrganizations.map(school => { const commercial = commercialsByOrg.get(school.id), current = commercial?.contract_status === "active" ? annualizeRecurringRevenue(Number(commercial.recurring_amount), commercial.billing_cycle as "monthly" | "quarterly" | "annual") : 0; return <Link href={`/platform/schools/${school.id}?view=school`} className="commercial-row" key={school.id}><span className="school-cell">{school.logo_url ? <i className="logo-thumb" style={{ backgroundImage: `url(${school.logo_url})` }} /> : <i>{school.name.slice(0, 2).toUpperCase()}</i>}<span><b>{school.name}</b><small>{commercial?.contract_status || "not configured"}</small></span></span><span><b>{commercial?.plan_name || "Pending"}</b><small>{commercial?.billing_cycle || "—"}</small></span><span><b>{money.format(current)}</b><small>Contracted</small></span><span><b>{money.format(forecastedAnnualRevenue(1))}</b><small>Fixed price</small></span><span><b>{commercial?.contract_ends_on || "No renewal date"}</b><small>{commercial?.licensed_students ? `${commercial.licensed_students} licensed` : "No licence cap"}</small></span></Link>; })}</div></section>}

    {view === "onboarding" && <div className="platform-tab-stack">
      <section className="card onboarding-form-card"><header className="card-header"><div><h2>Add school portfolio</h2><p>Create the tenant, all branches, commercial profile and multiple owner invitations in one controlled workflow.</p></div></header><SchoolPortfolioForm /></section>
      <section className="card tab-panel"><header className="card-header"><div><h2>Onboarding pipeline</h2><p>Schools that have not reached live operation, grouped by their current milestone.</p></div><span className="status status-warning">{pipelineSchools.length} IN PROGRESS</span></header><div className="pipeline-grid">{pipelineSchools.map(school => { const commercial = commercialsByOrg.get(school.id); return <Link href={`/platform/schools/${school.id}?view=school`} key={school.id}><span className="status status-warning">{school.onboarding_stage.replaceAll("_", " ")}</span><h3>{school.name}</h3><p>{branchCounts.get(school.id) || 0} branches · {studentCounts.get(school.id) || 0} students</p><b>{money.format(forecastedAnnualRevenue(1))} forecast</b><small>{commercial?.contract_status === "trial" ? `Pilot ends ${commercial.contract_ends_on || "pending"}` : commercial?.plan_name || "Commercials pending"}</small></Link>; })}{!pipelineSchools.length && <p className="empty-copy task-empty">Every non-deleted school is live.</p>}</div></section>
      <section className="card tab-panel"><header className="card-header"><div><h2>One-month pilots</h2><p>Free evaluations, enforced start and end dates, and conversion readiness.</p></div><span className="status">{activePilots.length} ACTIVE</span></header><div className="pilot-table">{pilotCommercials.map(commercial => { const school = activeOrganizations.find(item => item.id === commercial.organization_id), state = pilotState(commercial.contract_status, commercial.contract_ends_on); if (!school) return null; return <Link href={`/platform/schools/${school.id}?view=school`} key={school.id}><span className="school-cell">{school.logo_url ? <i className="logo-thumb" style={{ backgroundImage: `url(${school.logo_url})` }} /> : <i>{school.name.slice(0, 2).toUpperCase()}</i>}<span><b>{school.name}</b><small>{branchCounts.get(school.id) || 0} branches · {studentCounts.get(school.id) || 0} students</small></span></span><span><b>{commercial.contract_starts_on || "Start pending"}</b><small>Started</small></span><span><b>{commercial.contract_ends_on || "End pending"}</b><small>Ends after one month</small></span><span className={`status ${state === "expired" ? "status-warning" : ""}`}>{state}</span></Link>; })}{!pilotCommercials.length && <p className="empty-copy task-empty">No schools are currently in a pilot.</p>}</div></section>
    </div>}
  </div></main>;
}
