"use client";

import { useState } from "react";
import { createPlatformSchool } from "./actions";

const branch = { name: "", code: "", address: "", city: "", state: "", postal: "", latitude: "", longitude: "", email: "", phone: "" };
const owner = { name: "", email: "", phone: "", title: "School owner" };

export function SchoolPortfolioForm() {
  const [branches, setBranches] = useState([{ ...branch }]);
  const [owners, setOwners] = useState([{ ...owner }]);
  return <form action={createPlatformSchool} className="platform-form multipart-form">
    <fieldset><legend>School identity</legend><div className="split-fields"><label className="field">School name<input name="name" required maxLength={160}/></label><label className="field">Legal name<input name="legal_name" maxLength={200}/></label></div><div className="split-fields"><label className="field">URL slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="greenfield-school"/></label><label className="field">Website<input name="website_url" type="text" placeholder="school.edu.in"/></label></div><div className="split-fields"><label className="field">School type<select name="school_type" defaultValue="day_school"><option value="preschool">Preschool</option><option value="day_school">Day school</option><option value="day_boarding">Day boarding</option><option value="boarding">Boarding</option><option value="college">College</option><option value="other">Other</option></select></label><label className="field">Education board<select name="education_board" defaultValue="CBSE"><option>CBSE</option><option>CISCE</option><option>State board</option><option>IB</option><option>Cambridge</option><option>Other</option></select></label></div><div className="split-fields"><label className="field">Established year<input name="established_year" type="number" min="1800" max="2200"/></label><label className="field">Affiliation number<input name="affiliation_number" maxLength={80}/></label></div><div className="split-fields"><label className="field">School email<input name="primary_email" type="email"/></label><label className="field">School phone<input name="primary_phone" type="tel" maxLength={30}/></label></div><label className="field">Logo for tenant branding <small>PNG, JPEG or WebP · max 2 MB</small><input name="logo" type="file" accept="image/png,image/jpeg,image/webp"/></label></fieldset>
    <fieldset><legend>Branches</legend><p className="form-hint">Add every branch now. Exact addresses are required; coordinates improve map accuracy.</p>{branches.map((item,index)=><div className="repeat-block" key={index}><div className="repeat-head"><b>Branch {index+1}</b>{branches.length>1&&<button type="button" className="text-button" onClick={()=>setBranches((all)=>all.filter((_,i)=>i!==index))}>Remove</button>}</div><div className="split-fields"><label className="field">Name<input name="branch_name" required value={item.name} onChange={(e)=>setBranches(all=>all.map((x,i)=>i===index?{...x,name:e.target.value}:x))}/></label><label className="field">Code<input name="branch_code" required maxLength={24} value={item.code} onChange={(e)=>setBranches(all=>all.map((x,i)=>i===index?{...x,code:e.target.value}:x))} placeholder="MAIN"/></label></div><label className="field">Street address<input name="branch_address" required value={item.address} onChange={(e)=>setBranches(all=>all.map((x,i)=>i===index?{...x,address:e.target.value}:x))}/></label><div className="three-fields"><label className="field">City<input name="branch_city" required value={item.city} onChange={(e)=>setBranches(all=>all.map((x,i)=>i===index?{...x,city:e.target.value}:x))}/></label><label className="field">State<input name="branch_state" required value={item.state} onChange={(e)=>setBranches(all=>all.map((x,i)=>i===index?{...x,state:e.target.value}:x))}/></label><label className="field">PIN code<input name="branch_postal" value={item.postal} onChange={(e)=>setBranches(all=>all.map((x,i)=>i===index?{...x,postal:e.target.value}:x))}/></label></div><div className="split-fields"><label className="field">Latitude<input name="branch_latitude" type="number" step="any" min="-90" max="90" value={item.latitude} onChange={(e)=>setBranches(all=>all.map((x,i)=>i===index?{...x,latitude:e.target.value}:x))}/></label><label className="field">Longitude<input name="branch_longitude" type="number" step="any" min="-180" max="180" value={item.longitude} onChange={(e)=>setBranches(all=>all.map((x,i)=>i===index?{...x,longitude:e.target.value}:x))}/></label></div><div className="split-fields"><label className="field">Branch email<input name="branch_email" type="email" value={item.email} onChange={(e)=>setBranches(all=>all.map((x,i)=>i===index?{...x,email:e.target.value}:x))}/></label><label className="field">Branch phone<input name="branch_phone" value={item.phone} onChange={(e)=>setBranches(all=>all.map((x,i)=>i===index?{...x,phone:e.target.value}:x))}/></label></div></div>)}<button type="button" className="secondary" onClick={()=>setBranches((all)=>[...all,{...branch}])}>+ Add another branch</button></fieldset>
    <fieldset><legend>School owners</legend><p className="form-hint">Each owner receives a secure invitation. The first owner is the primary contact.</p>{owners.map((item,index)=><div className="repeat-block" key={index}><div className="repeat-head"><b>{index===0?"Primary owner":`Owner ${index+1}`}</b>{owners.length>1&&<button type="button" className="text-button" onClick={()=>setOwners((all)=>all.filter((_,i)=>i!==index))}>Remove</button>}</div><div className="split-fields"><label className="field">Full name<input name="owner_name" required value={item.name} onChange={(e)=>setOwners(all=>all.map((x,i)=>i===index?{...x,name:e.target.value}:x))}/></label><label className="field">Email<input name="owner_email" type="email" required value={item.email} onChange={(e)=>setOwners(all=>all.map((x,i)=>i===index?{...x,email:e.target.value}:x))}/></label></div><div className="split-fields"><label className="field">Phone<input name="owner_phone" value={item.phone} onChange={(e)=>setOwners(all=>all.map((x,i)=>i===index?{...x,phone:e.target.value}:x))}/></label><label className="field">Job title<input name="owner_title" value={item.title} onChange={(e)=>setOwners(all=>all.map((x,i)=>i===index?{...x,title:e.target.value}:x))}/></label></div></div>)}<button type="button" className="secondary" onClick={()=>setOwners((all)=>[...all,{...owner}])}>+ Invite another owner</button></fieldset>
    <fieldset><legend>Commercial & onboarding</legend><div className="split-fields"><label className="field">Plan<input name="plan_name" defaultValue="Standard" required/></label><label className="field">Customer success owner<input name="customer_success_owner"/></label></div><div className="three-fields"><label className="field">Billing cycle<select name="billing_cycle" defaultValue="annual"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option></select></label><label className="field">Recurring amount (₹)<input name="recurring_amount" type="number" min="0" step="0.01" defaultValue="0" required/></label><label className="field">Implementation fee (₹)<input name="implementation_fee" type="number" min="0" step="0.01" defaultValue="0"/></label></div><div className="three-fields"><label className="field">Contract status<select name="contract_status" defaultValue="trial"><option value="trial">Trial</option><option value="active">Active</option><option value="paused">Paused</option><option value="expired">Expired</option></select></label><label className="field">Starts on<input name="contract_starts_on" type="date"/></label><label className="field">Ends on<input name="contract_ends_on" type="date"/></label></div><label className="field">Licensed students<input name="licensed_students" type="number" min="0"/></label></fieldset>
    <button className="primary">Create school, branches and invite owners</button>
  </form>;
}
