"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { getUserContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { databaseId } from "@/lib/validation";
export type TransportState={error?:string;success?:string};
const managers=["owner","administrator","principal","staff"];
async function access(){const context=await getUserContext(),supabase=await createClient();return context&&supabase&&managers.includes(context.role)?{context,supabase}:null}
export async function createVehicle(_:TransportState,fd:FormData):Promise<TransportState>{const a=await access();if(!a)return{error:"Transport access is required."};const p=z.object({campus_id:databaseId,registration_number:z.string().trim().min(2).max(30),label:z.string().trim().min(1).max(80),capacity:z.coerce.number().int().min(1).max(100),driver_name:z.string().trim().max(120),driver_phone:z.string().trim().max(30)}).safeParse(Object.fromEntries(fd));if(!p.success)return{error:"Complete the vehicle details."};const{error}=await a.supabase.from("transport_vehicles").insert({...p.data,organization_id:a.context.organizationId,registration_number:p.data.registration_number.toUpperCase(),driver_name:p.data.driver_name||null,driver_phone:p.data.driver_phone||null});if(error)return{error:error.code==="23505"?"That registration number already exists.":error.message};revalidatePath("/dashboard/transport");return{success:"Vehicle added."}}
export async function createRoute(_:TransportState,fd:FormData):Promise<TransportState>{const a=await access();if(!a)return{error:"Transport access is required."};const p=z.object({campus_id:databaseId,vehicle_id:z.union([databaseId,z.literal("")]),name:z.string().trim().min(1).max(120),code:z.string().trim().min(1).max(24),morning_departure:z.string(),afternoon_departure:z.string()}).safeParse(Object.fromEntries(fd));if(!p.success)return{error:"Complete the route details."};const{error}=await a.supabase.from("transport_routes").insert({...p.data,organization_id:a.context.organizationId,vehicle_id:p.data.vehicle_id||null,code:p.data.code.toUpperCase(),morning_departure:p.data.morning_departure||null,afternoon_departure:p.data.afternoon_departure||null});if(error)return{error:error.code==="23505"?"That route code already exists.":error.message};revalidatePath("/dashboard/transport");return{success:"Route created."}}
export async function createStop(_:TransportState,fd:FormData):Promise<TransportState>{const a=await access();if(!a)return{error:"Transport access is required."};const p=z.object({route_id:databaseId,name:z.string().trim().min(1).max(160),stop_order:z.coerce.number().int().min(1).max(200),pickup_time:z.string(),drop_time:z.string()}).safeParse(Object.fromEntries(fd));if(!p.success)return{error:"Complete the stop details."};const{error}=await a.supabase.from("transport_stops").insert({...p.data,organization_id:a.context.organizationId,pickup_time:p.data.pickup_time||null,drop_time:p.data.drop_time||null});if(error)return{error:error.code==="23505"?"That stop order is already used on this route.":error.message};revalidatePath("/dashboard/transport");return{success:"Stop added."}}
export async function assignStudent(_:TransportState,fd:FormData):Promise<TransportState>{const a=await access();if(!a)return{error:"Transport access is required."};const p=z.object({student_id:databaseId,route_id:databaseId,stop_id:databaseId,starts_on:z.iso.date()}).safeParse(Object.fromEntries(fd));if(!p.success)return{error:"Choose a student, route and stop."};const existing=await a.supabase.from("transport_assignments").select("id").eq("organization_id",a.context.organizationId).eq("student_id",p.data.student_id).eq("status","active").maybeSingle();if(existing.error)return{error:existing.error.message};const result=existing.data?await a.supabase.from("transport_assignments").update({route_id:p.data.route_id,stop_id:p.data.stop_id,starts_on:p.data.starts_on}).eq("id",existing.data.id):await a.supabase.from("transport_assignments").insert({...p.data,organization_id:a.context.organizationId,status:"active"});if(result.error)return{error:result.error.message};revalidatePath("/dashboard/transport");return{success:"Student transport assigned."}}
export async function publishTransportAlert(_:TransportState,fd:FormData):Promise<TransportState>{const a=await access();if(!a)return{error:"Transport access is required."};const p=z.object({route_id:databaseId,title:z.string().trim().min(1).max(160),message:z.string().trim().min(1).max(1000),severity:z.enum(["info","delay","critical"])}).safeParse(Object.fromEntries(fd));if(!p.success)return{error:"Complete the alert."};const{error}=await a.supabase.from("transport_alerts").insert({...p.data,organization_id:a.context.organizationId,created_by:a.context.userId});if(error)return{error:error.message};revalidatePath("/dashboard/transport");return{success:"Transport alert published in Northstar."}}
