import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { AlertForm,AssignmentForm,RouteForm,StopForm,VehicleForm } from "@/components/transport/transport-forms";
import { getUserContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
export default async function TransportPage(){const context=await getUserContext();if(!context)redirect("/login?next=/dashboard/transport");const supabase=await createClient();if(!supabase)redirect("/login");const manager=["owner","administrator","principal","staff"].includes(context.role);
 const[campusesResult,vehiclesResult,routesResult,stopsResult,studentsResult,assignmentsResult,alertsResult]=await Promise.all([
  supabase.from("campuses").select("id,name").eq("organization_id",context.organizationId).order("name"),supabase.from("transport_vehicles").select("id,label,registration_number,capacity,driver_name,driver_phone,status").eq("organization_id",context.organizationId).order("label"),supabase.from("transport_routes").select("id,name,code,vehicle_id,morning_departure,afternoon_departure,status").eq("organization_id",context.organizationId).order("name"),supabase.from("transport_stops").select("id,route_id,name,stop_order,pickup_time,drop_time").eq("organization_id",context.organizationId).order("stop_order"),supabase.from("students").select("id,first_name,last_name,admission_number").eq("organization_id",context.organizationId).eq("status","active").order("first_name").limit(1000),supabase.from("transport_assignments").select("id,student_id,route_id,stop_id,status").eq("organization_id",context.organizationId).eq("status","active"),supabase.from("transport_alerts").select("id,route_id,title,message,severity,status,published_at").eq("organization_id",context.organizationId).eq("status","active").order("published_at",{ascending:false}).limit(50)
 ]);if([campusesResult,vehiclesResult,routesResult,stopsResult,studentsResult,assignmentsResult,alertsResult].some(x=>x.error))throw new Error("Transport information could not be loaded.");const campuses=campusesResult.data||[],vehicles=vehiclesResult.data||[],routes=routesResult.data||[],stops=stopsResult.data||[],students=studentsResult.data||[],assignments=assignmentsResult.data||[],alerts=alertsResult.data||[];const vehicleMap=new Map(vehicles.map(x=>[x.id,x])),studentMap=new Map(students.map(x=>[x.id,`${x.first_name} ${x.last_name||""}`.trim()])),stopMap=new Map(stops.map(x=>[x.id,x]));const assignedByRoute=new Map<string,number>();for(const a of assignments)assignedByRoute.set(a.route_id,(assignedByRoute.get(a.route_id)||0)+1);
 return <AppShell context={context} activePath="/dashboard/transport" pageTitle="Transport"><div className="page-head"><div><span className="eyebrow">SCHOOL TRANSPORT</span><h1>Every route, rider and delay.</h1><p>{manager?"Set up routes and give families one reliable place for daily transport information.":"View assigned routes, stops, timings and active service alerts."}</p></div></div>
 {alerts.length>0&&<section className="transport-alerts" aria-label="Active transport alerts">{alerts.map(a=><article className={`transport-alert alert-${a.severity}`} key={a.id}><span>{a.severity==="critical"?"!":"⌖"}</span><div><b>{a.title}</b><p>{a.message}</p><small>{new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(new Date(a.published_at))}</small></div></article>)}</section>}
 <section className="student-metrics"><div><span>Active routes</span><strong>{routes.filter(x=>x.status==="active").length}</strong><small>Configured services</small></div><div><span>Vehicles</span><strong>{vehicles.length}</strong><small>{vehicles.filter(x=>x.status==="maintenance").length} in maintenance</small></div><div><span>Assigned riders</span><strong>{assignments.length}</strong><small>Active allocations</small></div><div><span>Active alerts</span><strong>{alerts.length}</strong><small>In-app notices</small></div></section>
 <div className={`workflow-layout ${manager?"":"workflow-single"}`}><section className="card"><header className="card-header"><div><h2>{manager?"Route operations":"My transport"}</h2><p>Stops are shown in travel order.</p></div></header><div className="route-list">{routes.map(r=>{const v=r.vehicle_id?vehicleMap.get(r.vehicle_id):null,routeStops=stops.filter(s=>s.route_id===r.id),riders=assignments.filter(a=>a.route_id===r.id);return <details key={r.id} open={!manager&&routes.length===1}><summary><span className="route-code">{r.code}</span><div><b>{r.name}</b><small>{v?`${v.label} · ${v.registration_number}`:"Vehicle not assigned"}</small></div><span>{assignedByRoute.get(r.id)||0} riders</span></summary><div className="route-detail">{v&&(v.driver_name||v.driver_phone)&&<p><b>Driver:</b> {v.driver_name||"Not named"}{v.driver_phone?` · ${v.driver_phone}`:""}</p>}<ol>{routeStops.map(s=><li key={s.id}><span>{s.stop_order}</span><b>{s.name}</b><small>Pickup {s.pickup_time?.slice(0,5)||"—"} · Drop {s.drop_time?.slice(0,5)||"—"}</small></li>)}</ol>{!routeStops.length&&<p className="empty-copy">No stops configured.</p>}{!manager&&riders.map(a=><p className="my-stop" key={a.id}><b>{studentMap.get(a.student_id)}:</b> {stopMap.get(a.stop_id)?.name||"Assigned stop"}</p>)}</div></details>})}{!routes.length&&<p className="empty-copy task-empty">{manager?"Create the first route to begin transport setup.":"No active transport assignment is linked to this account."}</p>}</div></section>
 {manager&&<aside className="transport-setup"><details className="card" open={!vehicles.length}><summary className="setup-summary">1 · Add vehicle</summary><div className="card-body"><VehicleForm campuses={campuses}/></div></details><details className="card" open={vehicles.length>0&&!routes.length}><summary className="setup-summary">2 · Create route</summary><div className="card-body"><RouteForm campuses={campuses} vehicles={vehicles}/></div></details></aside>}</div>
 {manager&&routes.length>0&&<div className="operations-stack"><section className="card"><header className="card-header"><div><h2>Stops</h2><p>Add pickup and drop timings in route order.</p></div></header><div className="card-body"><StopForm routes={routes}/></div></section><section className="card"><header className="card-header"><div><h2>Student assignments</h2><p>One active route per student.</p></div></header><div className="card-body"><AssignmentForm students={students.map(x=>({id:x.id,label:`${studentMap.get(x.id)} · ${x.admission_number}`}))} routes={routes} stops={stops} today={today()}/></div></section><section className="card"><header className="card-header"><div><h2>Publish route alert</h2><p>Visible immediately to staff and families assigned to the route.</p></div></header><div className="card-body"><AlertForm routes={routes}/></div></section></div>}
 </AppShell>}
