"use client";

import { useActionState, useMemo, useState } from "react";
import { saveSubjectRegister, type ReportActionState } from "@/app/dashboard/report-cards/actions";

type Row = { reportCardId: string; studentId: string; name: string; admission: string; grade: string; percentage: number | null; comment: string };

export function SubjectReportRegister({ periodId, classId, allocationId, rows, grades, showPercentage, showComments, locked }: { periodId: string; classId: string; allocationId: string; rows: Row[]; grades: { grade: string; label: string }[]; showPercentage: boolean; showComments: boolean; locked: boolean }) {
  const [state, action, pending] = useActionState(saveSubjectRegister, {} as ReportActionState);
  const [values, setValues] = useState(rows), [search, setSearch] = useState("");
  const visible = useMemo(()=>values.map((row,index)=>({row,index})).filter(({row})=>`${row.name} ${row.admission}`.toLowerCase().includes(search.toLowerCase())),[values,search]);
  const complete = values.filter((row)=>row.grade.trim()).length;
  function update(index:number, patch:Partial<Row>){setValues((current)=>current.map((row,i)=>i===index?{...row,...patch}:row));}
  return <form action={action} className="subject-report-form"><input type="hidden" name="period_id" value={periodId}/><input type="hidden" name="class_id" value={classId}/><input type="hidden" name="class_subject_id" value={allocationId}/><input type="hidden" name="rows_json" value={JSON.stringify(values.map((row)=>({report_card_id:row.reportCardId,grade:row.grade,percentage:row.percentage,teacher_comment:row.comment})))}/><div className="marks-controls"><input type="search" value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search student or admission number" aria-label="Search report students"/><span><b>{complete}/{values.length}</b> grades complete</span></div>{state.error&&<p className="form-error register-message" role="alert">{state.error}</p>}{state.success&&<p className="form-success register-message" role="status">{state.success}</p>}<div className="report-table-wrap"><table className="report-table formal-register"><thead><tr><th>#</th><th>Student</th><th>Grade</th>{showPercentage&&<th>Percentage</th>}{showComments&&<th>Teacher comment</th>}</tr></thead><tbody>{visible.map(({row,index})=><tr key={row.reportCardId}><td>{String(index+1).padStart(2,"0")}</td><td><b>{row.name}</b><small>{row.admission}</small></td><td><select aria-label={`Grade for ${row.name}`} value={row.grade} onChange={(event)=>update(index,{grade:event.target.value})} disabled={locked}><option value="">Choose</option>{grades.map((item)=><option value={item.grade} key={item.grade}>{item.grade} · {item.label}</option>)}</select></td>{showPercentage&&<td><input aria-label={`Percentage for ${row.name}`} type="number" min="0" max="100" step="0.01" value={row.percentage??""} onChange={(event)=>update(index,{percentage:event.target.value===""?null:Number(event.target.value)})} disabled={locked}/></td>}{showComments&&<td><textarea aria-label={`Comment for ${row.name}`} rows={2} maxLength={1000} value={row.comment} onChange={(event)=>update(index,{comment:event.target.value})} disabled={locked} placeholder="Specific, evidence-based feedback"/></td>}</tr>)}</tbody></table></div><footer className="marks-footer"><span>{locked?"This register is locked after submission.":`${values.length-complete} grade${values.length-complete===1?"":"s"} remaining`}</span>{!locked&&<button className="primary compact" disabled={pending}><span>{pending?"Saving…":"Save subject register"}</span><span>→</span></button>}</footer></form>;
}
