begin;
create function pg_temp.id(n integer) returns uuid language sql immutable as $$ select ('00000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid $$;
create function pg_temp.assert_true(value boolean, message text) returns void language plpgsql as $$ begin if value is distinct from true then raise exception 'FAIL: %',message; end if; raise notice 'PASS: %',message; end $$;
create function pg_temp.reject(query text,message text) returns void language plpgsql as $$ declare rejected boolean:=false; begin begin execute query; exception when others then rejected:=true; end; perform pg_temp.assert_true(rejected,message); end $$;
insert into auth.users(id,email) select pg_temp.id(n),'audit'||n||'@example.test' from generate_series(1,5)n;
insert into public.organizations(id,name,slug) values(pg_temp.id(10),'Audit School','audit-school'),(pg_temp.id(11),'Other School','other-school');
insert into public.campuses(id,organization_id,name,code) values(pg_temp.id(20),pg_temp.id(10),'Main Campus','MC'),(pg_temp.id(21),pg_temp.id(10),'Other Campus','OC');
insert into public.academic_years(id,organization_id,name,starts_on,ends_on,status) values(pg_temp.id(30),pg_temp.id(10),'2026','2026-01-01','2026-12-31','active');
insert into public.memberships(organization_id,user_id,role) values(pg_temp.id(10),pg_temp.id(1),'owner'),(pg_temp.id(10),pg_temp.id(2),'teacher'),(pg_temp.id(10),pg_temp.id(3),'parent'),(pg_temp.id(11),pg_temp.id(4),'owner'),(pg_temp.id(10),pg_temp.id(5),'student');
insert into public.staff_profiles(id,organization_id,campus_id,user_id,employee_number,first_name,designation) values(pg_temp.id(40),pg_temp.id(10),pg_temp.id(20),pg_temp.id(2),'T1','Teacher','Teacher');
insert into public.students(id,organization_id,campus_id,user_id,admission_number,first_name) values(pg_temp.id(50),pg_temp.id(10),pg_temp.id(20),pg_temp.id(5),'S1','Student One'),(pg_temp.id(51),pg_temp.id(10),pg_temp.id(20),null,'S2','Student Two');
insert into public.guardians(id,organization_id,user_id,first_name,phone) values(pg_temp.id(60),pg_temp.id(10),pg_temp.id(3),'Parent','123');
insert into public.guardian_relationships(organization_id,student_id,guardian_id,guardian_user_id,relationship) values(pg_temp.id(10),pg_temp.id(50),pg_temp.id(60),pg_temp.id(3),'parent');
insert into public.classes(id,organization_id,campus_id,academic_year_id,grade,section) values(pg_temp.id(70),pg_temp.id(10),pg_temp.id(20),pg_temp.id(30),'1','A'),(pg_temp.id(71),pg_temp.id(10),pg_temp.id(20),pg_temp.id(30),'2','A');
insert into public.class_enrollments(organization_id,class_id,student_id) values(pg_temp.id(10),pg_temp.id(70),pg_temp.id(50)),(pg_temp.id(10),pg_temp.id(70),pg_temp.id(51));
insert into public.subjects(id,organization_id,name,code) values(pg_temp.id(80),pg_temp.id(10),'Math','M');
insert into public.class_subjects(id,organization_id,class_id,subject_id,teacher_staff_id) values(pg_temp.id(90),pg_temp.id(10),pg_temp.id(70),pg_temp.id(80),pg_temp.id(40)),(pg_temp.id(91),pg_temp.id(10),pg_temp.id(71),pg_temp.id(80),null);
insert into public.assessments(id,organization_id,class_subject_id,title,assessment_date,max_marks,created_by,status) values(pg_temp.id(100),pg_temp.id(10),pg_temp.id(90),'Test','2026-09-14',10,pg_temp.id(1),'marks_open');
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);
select pg_temp.assert_true(private.can_teach_class_subject(pg_temp.id(90),pg_temp.id(10)),'assigned teacher can teach');
select pg_temp.assert_true(not private.can_teach_class_subject(pg_temp.id(91),pg_temp.id(10)),'unassigned teacher denied');
select public.save_attendance_register(pg_temp.id(10),pg_temp.id(70),'2026-09-14',true,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','absent'),jsonb_build_object('student_id',pg_temp.id(51),'status','present')));
select pg_temp.assert_true((select count(*)=2 from public.attendance_records),'attendance register saved completely');
select pg_temp.reject($q$select public.save_attendance_register(pg_temp.id(10),pg_temp.id(70),'2026-09-15',true,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','present')))$q$,'incomplete roster rejected');
select pg_temp.assert_true((select count(*)=1 from public.attendance_sessions),'failed save left no session');
select pg_temp.reject($q$select public.save_marks_register(pg_temp.id(100),true,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','scored','marks',5),jsonb_build_object('student_id',pg_temp.id(51),'status','scored','marks',11)))$q$,'out-of-range marks rejected');
select pg_temp.assert_true((select count(*)=0 from public.assessment_marks),'failed mark batch rolled back');
select public.save_marks_register(pg_temp.id(100),false,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','scored','marks',5),jsonb_build_object('student_id',pg_temp.id(51),'status','absent','marks',null)));
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
select pg_temp.assert_true((select count(*)=0 from public.assessment_marks),'parent cannot read unpublished marks');
select pg_temp.assert_true((select count(*)=1 from public.students),'parent sees only linked student');
select pg_temp.assert_true((select count(*)=1 from public.class_enrollments),'parent cannot enumerate unrelated enrollments');
select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);
select public.save_marks_register(pg_temp.id(100),true,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','scored','marks',5),jsonb_build_object('student_id',pg_temp.id(51),'status','absent','marks',null)));
select pg_temp.reject($q$update public.assessment_marks set marks=6 where student_id=pg_temp.id(50)$q$,'published marks cannot be changed directly');
select pg_temp.reject($q$update public.assessments set status='marks_open' where id=pg_temp.id(100)$q$,'published assessment cannot be silently reopened');
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
select pg_temp.assert_true((select count(*)=1 from public.assessment_marks),'parent sees only linked published mark');
select set_config('request.jwt.claim.sub',pg_temp.id(5)::text,true);
select pg_temp.assert_true((select count(*)=1 from public.assessment_marks),'student sees own published mark');
select set_config('request.jwt.claim.sub',pg_temp.id(4)::text,true);
select pg_temp.assert_true((select count(*)=0 from public.students),'other organization cannot read students');
select pg_temp.assert_true((select count(*)=0 from public.assessment_marks),'other organization cannot read marks');
select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);
select pg_temp.reject($q$select public.create_homework_with_classes(pg_temp.id(10),pg_temp.id(80),'Test','Work','2026-09-15',30,true,array[pg_temp.id(70),pg_temp.id(71)])$q$,'homework denied for unassigned class');
select pg_temp.assert_true((select count(*)=0 from public.homework_assignments),'failed homework left no orphan');
select public.create_homework_with_classes(pg_temp.id(10),pg_temp.id(80),'Test','Work','2026-09-15',30,true,array[pg_temp.id(70)]);
select pg_temp.assert_true((select count(*)=1 from public.homework_classes),'homework class mapping saved');
reset role;
update public.attendance_sessions set status='locked';
set local role authenticated;
select pg_temp.reject($q$update public.attendance_records set status='present' where student_id=pg_temp.id(50)$q$,'locked attendance rejects direct writes');
select pg_temp.reject($q$select public.save_attendance_register(pg_temp.id(10),pg_temp.id(70),'2026-09-14',false,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','present'),jsonb_build_object('student_id',pg_temp.id(51),'status','present')))$q$,'locked attendance rejects RPC writes');
reset role;
update public.memberships set status='suspended' where user_id=pg_temp.id(2);
set local role authenticated;
select pg_temp.assert_true(not private.can_teach_class_subject(pg_temp.id(90),pg_temp.id(10)),'suspended teacher loses allocation access');
select pg_temp.assert_true((select count(*)=0 from public.assessment_marks),'suspended teacher loses marks access');
reset role;
select pg_temp.assert_true((select count(*)>0 from public.audit_events where action like 'attendance_records.batch_%'),'batched mutation audit exists');
select pg_temp.assert_true(not has_function_privilege('anon','public.save_marks_register(uuid,boolean,jsonb)','execute'),'anonymous RPC denied');
select pg_temp.reject($q$insert into public.timetable_entries(organization_id,class_id,class_subject_id,weekday,period_number,starts_at,ends_at) values(pg_temp.id(10),pg_temp.id(71),pg_temp.id(90),1,1,'09:00','10:00')$q$,'mismatched timetable allocation rejected');
insert into public.timetable_entries(organization_id,class_id,class_subject_id,weekday,period_number,starts_at,ends_at) values(pg_temp.id(10),pg_temp.id(70),pg_temp.id(90),1,1,'09:00','10:00');
select pg_temp.reject($q$insert into public.timetable_entries(organization_id,class_id,class_subject_id,weekday,period_number,starts_at,ends_at) values(pg_temp.id(10),pg_temp.id(70),pg_temp.id(90),1,2,'09:30','10:30')$q$,'overlapping timetable periods rejected');
rollback;
