begin;
create function pg_temp.id(n integer) returns uuid language sql immutable as $$ select ('00000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid $$;
create function pg_temp.assert_true(value boolean, message text) returns void language plpgsql as $$ begin if value is distinct from true then raise exception 'FAIL: %',message; end if; raise notice 'PASS: %',message; end $$;
create function pg_temp.reject(query text,message text) returns void language plpgsql as $$ declare rejected boolean:=false; begin begin execute query; exception when others then rejected:=true; end; perform pg_temp.assert_true(rejected,message); end $$;
insert into auth.users(id,email) select pg_temp.id(n),'audit'||n||'@example.test' from generate_series(1,6)n;
insert into public.organizations(id,name,slug) values(pg_temp.id(10),'Audit School','audit-school'),(pg_temp.id(11),'Other School','other-school');
insert into public.campuses(id,organization_id,name,code) values(pg_temp.id(20),pg_temp.id(10),'Main Campus','MC'),(pg_temp.id(21),pg_temp.id(10),'Other Campus','OC');
insert into public.academic_years(id,organization_id,name,starts_on,ends_on,status) values(pg_temp.id(30),pg_temp.id(10),'2026','2026-01-01','2026-12-31','active');
insert into public.memberships(organization_id,user_id,role) values(pg_temp.id(10),pg_temp.id(1),'owner'),(pg_temp.id(10),pg_temp.id(2),'teacher'),(pg_temp.id(10),pg_temp.id(3),'parent'),(pg_temp.id(11),pg_temp.id(4),'owner'),(pg_temp.id(10),pg_temp.id(5),'student'),(pg_temp.id(10),pg_temp.id(6),'administrator');
insert into public.staff_profiles(id,organization_id,campus_id,user_id,employee_number,first_name,designation) values(pg_temp.id(40),pg_temp.id(10),pg_temp.id(20),pg_temp.id(2),'T1','Teacher','Teacher');
insert into public.students(id,organization_id,campus_id,user_id,admission_number,first_name) values(pg_temp.id(50),pg_temp.id(10),pg_temp.id(20),pg_temp.id(5),'S1','Student One'),(pg_temp.id(51),pg_temp.id(10),pg_temp.id(20),null,'S2','Student Two');
insert into public.guardians(id,organization_id,user_id,first_name,phone) values(pg_temp.id(60),pg_temp.id(10),pg_temp.id(3),'Parent','123');
insert into public.guardian_relationships(organization_id,student_id,guardian_id,guardian_user_id,relationship) values(pg_temp.id(10),pg_temp.id(50),pg_temp.id(60),pg_temp.id(3),'parent');
insert into public.classes(id,organization_id,campus_id,academic_year_id,grade,section) values(pg_temp.id(70),pg_temp.id(10),pg_temp.id(20),pg_temp.id(30),'1','A'),(pg_temp.id(71),pg_temp.id(10),pg_temp.id(20),pg_temp.id(30),'2','A');
insert into public.class_enrollments(organization_id,class_id,student_id) values(pg_temp.id(10),pg_temp.id(70),pg_temp.id(50)),(pg_temp.id(10),pg_temp.id(70),pg_temp.id(51));
insert into public.subjects(id,organization_id,name,code) values(pg_temp.id(80),pg_temp.id(10),'Math','M');
insert into public.class_subjects(id,organization_id,class_id,subject_id,teacher_staff_id) values(pg_temp.id(90),pg_temp.id(10),pg_temp.id(70),pg_temp.id(80),pg_temp.id(40)),(pg_temp.id(91),pg_temp.id(10),pg_temp.id(71),pg_temp.id(80),null);
insert into public.assessments(id,organization_id,class_subject_id,title,assessment_date,max_marks,created_by,status) values(pg_temp.id(100),pg_temp.id(10),pg_temp.id(90),'Test','2026-09-14',10,pg_temp.id(1),'marks_open');
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);
select pg_temp.assert_true(private.can_teach_class_subject(pg_temp.id(90),pg_temp.id(10)),'assigned teacher can teach');
select pg_temp.assert_true(not private.can_teach_class_subject(pg_temp.id(91),pg_temp.id(10)),'unassigned teacher denied');
select public.save_attendance_register(pg_temp.id(10),pg_temp.id(70),'2026-09-14',true,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','absent'),jsonb_build_object('student_id',pg_temp.id(51),'status','present')));
select pg_temp.assert_true((select count(*)=2 from public.attendance_records),'attendance register saved completely');
select pg_temp.reject($q$select public.save_attendance_register(pg_temp.id(10),pg_temp.id(70),'2026-09-15',true,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','present')))$q$,'incomplete roster rejected');
select pg_temp.assert_true((select count(*)=1 from public.attendance_sessions),'failed save left no session');
select pg_temp.reject($q$select public.save_marks_register(pg_temp.id(100),true,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','scored','marks',5),jsonb_build_object('student_id',pg_temp.id(51),'status','scored','marks',11)))$q$,'out-of-range marks rejected');
select pg_temp.assert_true((select count(*)=0 from public.assessment_marks),'failed mark batch rolled back');
select public.save_marks_register(pg_temp.id(100),false,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','scored','marks',5),jsonb_build_object('student_id',pg_temp.id(51),'status','absent','marks',null)));
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
select pg_temp.assert_true((select count(*)=0 from public.assessment_marks),'parent cannot read unpublished marks');
select pg_temp.assert_true((select count(*)=1 from public.students),'parent sees only linked student');
select pg_temp.assert_true((select count(*)=1 from public.class_enrollments),'parent cannot enumerate unrelated enrollments');
select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);
select public.save_marks_register(pg_temp.id(100),true,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','scored','marks',5),jsonb_build_object('student_id',pg_temp.id(51),'status','absent','marks',null)));
select pg_temp.reject($q$update public.assessment_marks set marks=6 where student_id=pg_temp.id(50)$q$,'published marks cannot be changed directly');
select pg_temp.reject($q$update public.assessments set status='marks_open' where id=pg_temp.id(100)$q$,'published assessment cannot be silently reopened');
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
select pg_temp.assert_true((select count(*)=1 from public.assessment_marks),'parent sees only linked published mark');
select set_config('request.jwt.claim.sub',pg_temp.id(5)::text,true);
select pg_temp.assert_true((select count(*)=1 from public.assessment_marks),'student sees own published mark');
select set_config('request.jwt.claim.sub',pg_temp.id(4)::text,true);
select pg_temp.assert_true((select count(*)=0 from public.students),'other organization cannot read students');
select pg_temp.assert_true((select count(*)=0 from public.assessment_marks),'other organization cannot read marks');
select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);
select pg_temp.reject($q$select public.create_homework_with_classes(pg_temp.id(10),pg_temp.id(80),'Test','Work','2026-09-15',30,true,array[pg_temp.id(70),pg_temp.id(71)])$q$,'homework denied for unassigned class');
select pg_temp.assert_true((select count(*)=0 from public.homework_assignments),'failed homework left no orphan');
select public.create_homework_with_classes(pg_temp.id(10),pg_temp.id(80),'Test','Work','2026-09-15',30,true,array[pg_temp.id(70)]);
select pg_temp.assert_true((select count(*)=1 from public.homework_classes),'homework class mapping saved');
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
select pg_temp.assert_true((select count(*)=1 from public.homework_assignments),'parent sees published homework for linked student');
select pg_temp.reject($q$insert into public.homework_submissions(organization_id,homework_id,student_id,response,status,submitted_by,feedback) values(pg_temp.id(10),(select id from public.homework_assignments limit 1),pg_temp.id(50),'Done','submitted',pg_temp.id(3),'Forged feedback')$q$,'parent cannot forge teacher feedback');
insert into public.homework_submissions(organization_id,homework_id,student_id,response,status,submitted_by,submitted_at) values(pg_temp.id(10),(select id from public.homework_assignments limit 1),pg_temp.id(50),'Done','submitted',pg_temp.id(3),now());
select pg_temp.assert_true((select count(*)=1 from public.homework_submissions),'parent can submit linked student homework');
select pg_temp.reject($q$insert into public.homework_submissions(organization_id,homework_id,student_id,status,submitted_by) values(pg_temp.id(10),(select id from public.homework_assignments limit 1),pg_temp.id(51),'completed',pg_temp.id(3))$q$,'parent cannot submit another student homework');
insert into public.leave_requests(organization_id,student_id,leave_type,starts_on,ends_on,reason,requested_by) values(pg_temp.id(10),pg_temp.id(50),'sick','2026-09-15','2026-09-16','Fever',pg_temp.id(3));
select pg_temp.assert_true((select count(*)=1 from public.leave_requests),'parent can request linked student leave');
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
select pg_temp.assert_true((select count(*)=5 from public.list_organization_access(pg_temp.id(10))),'owner can list tenant-scoped access');
select pg_temp.assert_true(public.create_owned_school('Second Audit School','second-audit-school','Central Campus','CC') is not null,'owner can create another school atomically');
select pg_temp.assert_true((select count(*)=1 from public.organizations where slug='second-audit-school'),'created school is visible to its owner');
select pg_temp.assert_true((select count(*)=1 from public.memberships where organization_id=(select id from public.organizations where slug='second-audit-school') and user_id=pg_temp.id(1) and role='owner'),'school creation grants owner membership');
select set_config('request.jwt.claim.sub',pg_temp.id(6)::text,true);
select pg_temp.reject($q$update public.memberships set role='staff' where organization_id=pg_temp.id(10) and user_id=pg_temp.id(1)$q$,'administrator cannot demote owner through direct database access');
select pg_temp.reject($q$update public.memberships set role='administrator' where organization_id=pg_temp.id(10) and user_id=pg_temp.id(2)$q$,'administrator cannot grant administrator through direct database access');
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
select pg_temp.reject($q$insert into public.homework_submissions(organization_id,homework_id,student_id,status,submitted_by) values(pg_temp.id(10),(select id from public.homework_assignments limit 1),pg_temp.id(51),'completed',pg_temp.id(1))$q$,'administrator cannot impersonate a student submission');
insert into public.announcements(id,organization_id,title,body,audience,status,requires_acknowledgement,published_at,created_by) values(pg_temp.id(110),pg_temp.id(10),'Notice','Read this',array['parent']::public.app_role[],'published',true,now(),pg_temp.id(1));
insert into public.fee_invoices(id,organization_id,student_id,fee_name,amount,due_on,created_by) values(pg_temp.id(120),pg_temp.id(10),pg_temp.id(50),'Term fee',1000,'2026-10-01',pg_temp.id(1));
select pg_temp.reject($q$update public.fee_invoices set paid_amount=100,status='partial' where id=pg_temp.id(120)$q$,'invoice balance cannot be edited outside payment workflow');
select pg_temp.reject($q$insert into public.fee_payments(organization_id,invoice_id,amount,method,recorded_by) values(pg_temp.id(10),pg_temp.id(120),100,'cash',pg_temp.id(1))$q$,'direct payment inserts are denied');
select public.record_fee_payment(pg_temp.id(120),400,'upi','audit-ref');
select pg_temp.assert_true((select paid_amount=400 and status='partial' from public.fee_invoices where id=pg_temp.id(120)),'fee payment updates invoice atomically');
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
select pg_temp.assert_true((select count(*)=1 from public.announcements),'parent sees role-targeted announcement');
insert into public.announcement_receipts(organization_id,announcement_id,user_id,acknowledged_at) values(pg_temp.id(10),pg_temp.id(110),pg_temp.id(3),now());
select pg_temp.assert_true((select count(*)=1 from public.fee_invoices),'parent sees linked student invoice');
select pg_temp.assert_true((select count(*)=1 from public.fee_payments),'parent sees linked student payment');
select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);
update public.homework_submissions set status='completed',feedback='Good work',reviewed_by=pg_temp.id(2),reviewed_at=now();
select pg_temp.assert_true((select feedback='Good work' from public.homework_submissions),'assigned teacher can review homework response');
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
insert into public.attendance_corrections(id,organization_id,attendance_record_id,requested_by,requested_status,reason) values(pg_temp.id(125),pg_temp.id(10),(select id from public.attendance_records where student_id=pg_temp.id(50)),pg_temp.id(3),'present','Medical note supplied');
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
select public.review_attendance_correction(pg_temp.id(125),'approved');
select pg_temp.assert_true((select status='present' from public.attendance_records where student_id=pg_temp.id(50)),'approved correction updates attendance atomically');
select public.report_operational_incident(repeat('a',64),'/dashboard/attendance/:id');
select public.report_operational_incident(repeat('a',64),'/dashboard/attendance/:id');
select pg_temp.assert_true((select occurrence_count=2 from public.operational_incidents where fingerprint=repeat('a',64)),'incident reports deduplicate and count occurrences');
select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);
select pg_temp.reject($q$select public.list_organization_access(pg_temp.id(10))$q$,'teacher cannot enumerate organization access');
select pg_temp.reject($q$select public.create_owned_school('Forged School','forged-school','Main Campus','MC')$q$,'teacher cannot create a school tenant');
select public.report_operational_incident(repeat('b',64),'/dashboard/teacher');
select pg_temp.assert_true((select count(*)=0 from public.operational_incidents),'teacher can report but cannot read operational incidents');
select pg_temp.reject($q$insert into public.operational_incidents(organization_id,fingerprint,title,summary,reported_by) values(pg_temp.id(10),repeat('c',64),'Raw','Direct report',pg_temp.id(2))$q$,'members cannot bypass redacted incident RPC');
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
update public.operational_incidents set status='resolved',resolved_by=pg_temp.id(1),resolved_at=now() where fingerprint=repeat('a',64);
select pg_temp.assert_true((select status='resolved' from public.operational_incidents where fingerprint=repeat('a',64)),'owner can resolve an operational incident');
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
select public.set_notification_preferences(pg_temp.id(10),true,true,false);
select pg_temp.assert_true((select count(*)=3 from public.notification_preferences),'channel preferences save atomically');
select pg_temp.reject($q$insert into public.notifications(organization_id,user_id,title,body) values(pg_temp.id(10),pg_temp.id(3),'Forged','Message')$q$,'members cannot forge inbox notifications');
select pg_temp.reject($q$select public.create_announcement_with_notifications(pg_temp.id(10),null,'Forged','Message','normal',array['parent']::public.app_role[],false,null)$q$,'parent cannot publish notifications');
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
select public.create_announcement_with_notifications(pg_temp.id(10),null,'School update','Tomorrow is a regular school day.','important',array['parent','student']::public.app_role[],true,now()+interval '2 days');
reset role;
select pg_temp.assert_true((select count(*)=2 from public.notifications where title='School update'),'publication fans out once per matching active user');
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
select pg_temp.assert_true((select count(*)=2 from public.notification_deliveries where channel='in_app' and status='delivered'),'in-app delivery receipts are recorded');
select pg_temp.assert_true((select count(*)=1 from public.notification_deliveries where channel='email' and status='awaiting_provider'),'opted-in email waits safely for provider configuration');
select pg_temp.assert_true((select count(*)=0 from public.notification_deliveries where channel='sms'),'non-consented SMS is not queued');
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
select pg_temp.assert_true((select count(*)=1 from public.notifications where title='School update'),'parent reads only their notification');
update public.notifications set read_at=now() where title='School update';
select pg_temp.assert_true((select read_at is not null from public.notifications where title='School update'),'recipient can mark own notification read');
select set_config('request.jwt.claim.sub',pg_temp.id(4)::text,true);
select pg_temp.assert_true((select count(*)=0 from public.notifications),'other organization cannot read notifications');
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
insert into public.transport_vehicles(id,organization_id,campus_id,registration_number,label,capacity) values(pg_temp.id(130),pg_temp.id(10),pg_temp.id(20),'KA01TEST','Bus 1',1);
insert into public.transport_routes(id,organization_id,campus_id,vehicle_id,name,code) values(pg_temp.id(131),pg_temp.id(10),pg_temp.id(20),pg_temp.id(130),'Main Route','R1'),(pg_temp.id(132),pg_temp.id(10),pg_temp.id(20),null,'Unrelated Route','R2');
insert into public.transport_stops(id,organization_id,route_id,name,stop_order) values(pg_temp.id(133),pg_temp.id(10),pg_temp.id(131),'First Stop',1),(pg_temp.id(134),pg_temp.id(10),pg_temp.id(132),'Other Stop',1);
insert into public.transport_assignments(organization_id,student_id,route_id,stop_id) values(pg_temp.id(10),pg_temp.id(50),pg_temp.id(131),pg_temp.id(133));
select pg_temp.reject($q$insert into public.transport_assignments(organization_id,student_id,route_id,stop_id) values(pg_temp.id(10),pg_temp.id(51),pg_temp.id(131),pg_temp.id(134))$q$,'transport stop must belong to selected route');
select pg_temp.reject($q$insert into public.transport_assignments(organization_id,student_id,route_id,stop_id) values(pg_temp.id(10),pg_temp.id(51),pg_temp.id(131),pg_temp.id(133))$q$,'vehicle capacity is enforced');
insert into public.transport_alerts(organization_id,route_id,title,message,created_by) values(pg_temp.id(10),pg_temp.id(131),'Delay','Ten minutes late',pg_temp.id(1));
insert into public.school_events(organization_id,title,category,starts_at,ends_at,audience,created_by) values(pg_temp.id(10),'Parent meeting','meeting',now()+interval '1 day',now()+interval '2 hours 1 day',array['parent']::public.app_role[],pg_temp.id(1));
select set_config('request.jwt.claim.sub',pg_temp.id(3)::text,true);
select pg_temp.assert_true((select count(*)=1 from public.transport_routes),'parent sees only assigned transport route');
select pg_temp.assert_true((select count(*)=1 from public.transport_stops),'parent sees only assigned route stops');
select pg_temp.assert_true((select count(*)=1 from public.transport_alerts),'parent sees assigned route alert');
select pg_temp.assert_true((select count(*)=1 from public.school_events),'parent sees targeted calendar event');
select set_config('request.jwt.claim.sub',pg_temp.id(2)::text,true);
reset role;
update public.attendance_sessions set status='locked';
set local role authenticated;
select pg_temp.reject($q$update public.attendance_records set status='present' where student_id=pg_temp.id(50)$q$,'locked attendance rejects direct writes');
select pg_temp.reject($q$select public.save_attendance_register(pg_temp.id(10),pg_temp.id(70),'2026-09-14',false,jsonb_build_array(jsonb_build_object('student_id',pg_temp.id(50),'status','present'),jsonb_build_object('student_id',pg_temp.id(51),'status','present')))$q$,'locked attendance rejects RPC writes');
reset role;
update public.memberships set status='suspended' where user_id=pg_temp.id(2);
set local role authenticated;
select pg_temp.assert_true(not private.can_teach_class_subject(pg_temp.id(90),pg_temp.id(10)),'suspended teacher loses allocation access');
select pg_temp.assert_true((select count(*)=0 from public.assessment_marks),'suspended teacher loses marks access');
reset role;
select pg_temp.assert_true((select count(*)>0 from public.audit_events where action like 'attendance_records.batch_%'),'batched mutation audit exists');
select pg_temp.assert_true(not has_function_privilege('anon','public.save_marks_register(uuid,boolean,jsonb)','execute'),'anonymous RPC denied');
select pg_temp.reject($q$insert into public.timetable_entries(organization_id,class_id,class_subject_id,weekday,period_number,starts_at,ends_at) values(pg_temp.id(10),pg_temp.id(71),pg_temp.id(90),1,1,'09:00','10:00')$q$,'mismatched timetable allocation rejected');
insert into public.timetable_entries(organization_id,class_id,class_subject_id,weekday,period_number,starts_at,ends_at) values(pg_temp.id(10),pg_temp.id(70),pg_temp.id(90),1,1,'09:00','10:00');
select pg_temp.reject($q$insert into public.timetable_entries(organization_id,class_id,class_subject_id,weekday,period_number,starts_at,ends_at) values(pg_temp.id(10),pg_temp.id(70),pg_temp.id(90),1,2,'09:30','10:30')$q$,'overlapping timetable periods rejected');
reset role;
select pg_temp.assert_true(not has_function_privilege('authenticated','public.platform_create_school(text,text,text,text,uuid,uuid)','execute'),'school members cannot call platform provisioning RPC');
select pg_temp.assert_true(has_function_privilege('service_role','public.platform_create_school(text,text,text,text,uuid,uuid)','execute'),'trusted service role can call platform provisioning RPC');
set local role service_role;
select public.platform_create_school('Platform School','platform-school','Main Branch','PB',pg_temp.id(6),pg_temp.id(1));
reset role;
select pg_temp.assert_true((select count(*)=1 from public.organizations where slug='platform-school'),'platform provisioning creates a tenant atomically');
select pg_temp.assert_true((select count(*)=1 from public.memberships where organization_id=(select id from public.organizations where slug='platform-school') and user_id=pg_temp.id(6) and role='owner'),'platform provisioning grants the nominated owner');
select pg_temp.assert_true(not has_function_privilege('authenticated','public.platform_create_school_portfolio(text,text,text,text,text,text,text,integer,text,text,text,text,jsonb,jsonb,text,text,numeric,numeric,text,date,date,integer,uuid)','execute'),'school members cannot call portfolio provisioning');
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
select pg_temp.reject($q$select * from public.organization_commercials$q$,'commercial portfolio is hidden from school accounts');
select pg_temp.reject($q$select * from public.organization_owner_profiles$q$,'platform owner directory is hidden from school accounts');
reset role;
set local role service_role;
select public.platform_create_school_portfolio(
  'Portfolio School','portfolio-school','Portfolio School Trust','https://portfolio.example','',
  'day_school','CBSE',2001,'AFF-1','hello@portfolio.example','9999999999','Success Owner',
  '[{"name":"Central Branch","code":"CENTRAL","address_line1":"1 School Road","city":"Bengaluru","state":"Karnataka","postal_code":"560001","country":"India","latitude":12.971599,"longitude":77.594566}]'::jsonb,
  format('[{"user_id":"%s","job_title":"Trustee","phone":"9999999999","is_primary":true}]',pg_temp.id(5))::jsonb,
  'Growth','monthly',10000,5000,'active','2026-09-01','2027-08-31',500,pg_temp.id(1)
);
reset role;
select pg_temp.assert_true((select count(*)=1 from public.organizations where slug='portfolio-school' and website_url='https://portfolio.example'),'portfolio provisioning saves school identity');
select pg_temp.assert_true((select count(*)=1 from public.campuses where organization_id=(select id from public.organizations where slug='portfolio-school') and city='Bengaluru'),'portfolio provisioning saves exact branch data');
select pg_temp.assert_true((select recurring_amount=10000 and billing_cycle='monthly' from public.organization_commercials where organization_id=(select id from public.organizations where slug='portfolio-school')),'portfolio provisioning saves commercial terms');
select pg_temp.assert_true((select count(*)=1 from public.organization_owner_profiles where organization_id=(select id from public.organizations where slug='portfolio-school') and is_primary),'portfolio provisioning saves accountable owners');
select pg_temp.assert_true(not has_function_privilege('authenticated','public.platform_add_school_branches(uuid,jsonb,uuid)','execute'),'school members cannot call platform branch management');
set local role service_role;
select public.platform_update_school_portfolio(pg_temp.id(10),'https://updated.example','','boarding','CISCE',2002,'AFF-2','office@updated.example','8888888888','live','2026-09-16','CS Owner','Enterprise','annual',120000,10000,'active','2026-09-01','2027-08-31',800,pg_temp.id(1));
select public.platform_add_school_branches(pg_temp.id(10),'[{"name":"North Branch","code":"NORTH","address_line1":"2 School Road","city":"Bengaluru","state":"Karnataka","country":"India"}]'::jsonb,pg_temp.id(1));
select public.platform_update_school_branch(pg_temp.id(10),(select pg_temp.id(21)),'3 Updated Road','Mysuru','Karnataka','570001',12.3,76.6,'north@example.test','8888888888',pg_temp.id(1));
select public.platform_add_school_owners(pg_temp.id(10),format('[{"user_id":"%s","job_title":"Director","phone":"7777777777","is_primary":false}]',pg_temp.id(4))::jsonb,pg_temp.id(1));
reset role;
select pg_temp.assert_true((select onboarding_stage='live' and website_url='https://updated.example' from public.organizations where id=pg_temp.id(10)),'platform can enrich an existing school profile');
select pg_temp.assert_true((select recurring_amount=120000 and licensed_students=800 from public.organization_commercials where organization_id=pg_temp.id(10)),'platform can update existing school commercials atomically');
select pg_temp.assert_true((select address_line1='3 Updated Road' and city='Mysuru' from public.campuses where id=pg_temp.id(21)),'platform can update branch locations');
select pg_temp.assert_true((select count(*)=1 from public.campuses where organization_id=pg_temp.id(10) and code='NORTH'),'platform can add branches to an existing school');
select pg_temp.assert_true((select count(*)=1 from public.organization_owner_profiles where organization_id=pg_temp.id(10) and user_id=pg_temp.id(4)),'platform can add accountable owners to an existing school');
select pg_temp.assert_true(not has_function_privilege('authenticated','public.platform_set_school_archived(uuid,boolean,text,uuid)','execute'),'school members cannot archive tenants');
set local role service_role;
select public.platform_update_school_portfolio(pg_temp.id(10),'https://updated.example','','boarding','CISCE',2002,'AFF-2','office@updated.example','8888888888','live','2026-09-16','CS Owner','Pilot','annual',300000,10000,'trial','2026-09-16','2027-08-31',800,pg_temp.id(1));
reset role;
select pg_temp.assert_true((select recurring_amount=0 and contract_starts_on='2026-09-16' and contract_ends_on='2026-10-16' from public.organization_commercials where organization_id=pg_temp.id(10)),'one-month pilots are free and have an enforced calendar-month term');
set local role service_role;
select public.platform_set_school_archived(pg_temp.id(10),true,'Contract ended',pg_temp.id(1));
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
select pg_temp.assert_true(not private.has_org_role(pg_temp.id(10),array['owner']::public.app_role[]),'archived school access is disabled immediately');
reset role;
select pg_temp.assert_true((select status='archived' and archive_reason='Contract ended' from public.organizations where id=pg_temp.id(10)),'school deletion retains an archived portfolio record');
set local role service_role;
select public.platform_set_school_archived(pg_temp.id(10),false,'',pg_temp.id(1));
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',pg_temp.id(1)::text,true);
select pg_temp.assert_true(private.has_org_role(pg_temp.id(10),array['owner']::public.app_role[]),'restoring a school restores its existing owner assignment');
reset role;
select pg_temp.assert_true(not has_function_privilege('authenticated','public.platform_school_metrics(uuid)','execute'),'school members cannot call platform KPI aggregation');
set local role service_role;
select pg_temp.assert_true(((public.platform_school_metrics(pg_temp.id(10))->>'students_active')::integer)=2,'platform KPI aggregation reports active students');
select pg_temp.assert_true(((public.platform_school_metrics(pg_temp.id(10))->>'workflow_events')::integer)>0,'platform KPI aggregation reports audited workflow activity');
reset role;
set local role anon;
select pg_temp.assert_true(public.health_check(),'anonymous health probe confirms connectivity without tenant data');
rollback;
