"use client";
import { useState } from "react";
import { addPlatformBranches, invitePlatformOwners } from "../../actions";

const blankBranch={name:"",code:"",address:"",city:"",state:"",postal:"",latitude:"",longitude:"",email:"",phone:""};
const blankOwner={name:"",email:"",phone:"",title:"School owner"};

export function AddBranchesForm({organizationId}:{organizationId:string}){const[rows,setRows]=useState([{...blankBranch}]);return <form action={addPlatformBranches} className="platform-form"><input type="hidden" name="organization_id" value={organizationId}/>{rows.map((row,index)=><div className="repeat-block" key={index}><div className="repeat-head"><b>New branch {index+1}</b>{rows.length>1&&<button type="button" className="text-button" onClick={()=>setRows(all=>all.filter((_,i)=>i!==index))}>Remove</button>}</div><div className="split-fields"><label className="field">Name<input name="new_branch_name" required value={row.name} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,name:e.target.value}:item))}/></label><label className="field">Code<input name="new_branch_code" required value={row.code} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,code:e.target.value}:item))}/></label></div><label className="field">Street address<input name="new_branch_address" required value={row.address} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,address:e.target.value}:item))}/></label><div className="three-fields"><label className="field">City<input name="new_branch_city" required value={row.city} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,city:e.target.value}:item))}/></label><label className="field">State<input name="new_branch_state" required value={row.state} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,state:e.target.value}:item))}/></label><label className="field">PIN<input name="new_branch_postal" value={row.postal} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,postal:e.target.value}:item))}/></label></div><div className="split-fields"><label className="field">Latitude<input name="new_branch_latitude" type="number" step="any" value={row.latitude} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,latitude:e.target.value}:item))}/></label><label className="field">Longitude<input name="new_branch_longitude" type="number" step="any" value={row.longitude} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,longitude:e.target.value}:item))}/></label></div><div className="split-fields"><label className="field">Email<input name="new_branch_email" type="email" value={row.email} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,email:e.target.value}:item))}/></label><label className="field">Phone<input name="new_branch_phone" value={row.phone} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,phone:e.target.value}:item))}/></label></div></div>)}<div className="form-actions"><button type="button" className="secondary" onClick={()=>setRows(all=>[...all,{...blankBranch}])}>+ Another branch</button><button className="primary">Add {rows.length} branch{rows.length===1?"":"es"}</button></div></form>}

export function InviteOwnersForm({organizationId}:{organizationId:string}){const[rows,setRows]=useState([{...blankOwner}]);return <form action={invitePlatformOwners} className="platform-form"><input type="hidden" name="organization_id" value={organizationId}/>{rows.map((row,index)=><div className="repeat-block" key={index}><div className="repeat-head"><b>Additional owner {index+1}</b>{rows.length>1&&<button type="button" className="text-button" onClick={()=>setRows(all=>all.filter((_,i)=>i!==index))}>Remove</button>}</div><div className="split-fields"><label className="field">Full name<input name="new_owner_name" required value={row.name} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,name:e.target.value}:item))}/></label><label className="field">Email<input name="new_owner_email" type="email" required value={row.email} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,email:e.target.value}:item))}/></label></div><div className="split-fields"><label className="field">Phone<input name="new_owner_phone" value={row.phone} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,phone:e.target.value}:item))}/></label><label className="field">Job title<input name="new_owner_title" value={row.title} onChange={e=>setRows(all=>all.map((item,i)=>i===index?{...item,title:e.target.value}:item))}/></label></div></div>)}<div className="form-actions"><button type="button" className="secondary" onClick={()=>setRows(all=>[...all,{...blankOwner}])}>+ Another owner</button><button className="primary">Invite {rows.length} owner{rows.length===1?"":"s"}</button></div></form>}
