import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { isPlatformOwnerEmail } from "@/lib/auth/platform";
import { annualizeRecurringRevenue } from "@/lib/platform/portfolio";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
export default async function SchoolPortfolioPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params,client=await createClient();const {data:{user}}=client?await client.auth.getUser():{data:{user:null}};if(!user)redirect(`/login?next=/platform/schools/${id}`);if(!isPlatformOwnerEmail(user.email))redirect("/dashboard");const admin=createAdminClient();if(!admin)throw new Error("Platform administration is not configured.");
  const [schoolResult,branchesResult,studentsResult,staffResult,commercialResult,ownersResult,ownerMembershipsResult,usersResult]=await Promise.all([
    admin.from("organizations").select("*").eq("id",id).maybeSingle(),admin.from("campuses").select("*").eq("organization_id",id).order("name"),admin.from("students").select("id,campus_id,status").eq("organization_id",id),admin.from("staff_profiles").select("id,campus_id,status,designation").eq("organization_id",id),admin.from("organization_commercials").select("*").eq("organization_id",id).maybeSingle(),admin.from("organization_owner_profiles").select("*").eq("organization_id",id).order("is_primary",{ascending:false}),admin.from("memberships").select("id,user_id").eq("organization_id",id).eq("role","owner").eq("status","active"),admin.auth.admin.listUsers({page:1,perPage:1000}),
  ]);if(schoolResult.error)throw new Error("The school portfolio could not be loaded.");if(!schoolResult.data)notFound();const school=schoolResult.data,branches=branchesResult.data||[],students=studentsResult.data||[],staff=staffResult.data||[],commercial=commercialResult.data,users=new Map((usersResult.data?.users||[]).map(entry=>[entry.id,entry]));const teachers=staff.filter(item=>/teacher|faculty|educator/i.test(item.designation));const arr=commercial?annualizeRecurringRevenue(Number(commercial.recurring_amount),commercial.billing_cycle as "monthly"|"quarterly"|"annual"):0;
  return <main className="platform-page"><header className="platform-topbar"><Link className="brand" href="/platform"><span className="brand-mark"><i/><i/><i/></span><span>Northstar Platform</span></Link><Link className="secondary compact" href="/platform">← Portfolio</Link></header><div className="platform-content"><div className="page-head"><div><span className="eyebrow">SCHOOL PORTFOLIO</span><h1>{school.name}</h1><p>{school.legal_name||school.slug} · {school.education_board||school.school_type.replaceAll("_"," ")}</p></div>{school.logo_url?<i className="school-profile-logo" style={{backgroundImage:`url(${school.logo_url})`}}/>:<span className="tenant-avatar large-avatar">{school.name.slice(0,2).toUpperCase()}</span>}</div>
  <section className="platform-metrics"><article><span>Branches</span><strong>{branches.length}</strong><small>{branches.filter(item=>item.status==="active").length} active</small></article><article><span>Students</span><strong>{students.filter(item=>item.status==="active").length}</strong><small>{commercial?.licensed_students?`${commercial.licensed_students} licensed`:"No licence cap"}</small></article><article><span>Workforce</span><strong>{staff.filter(item=>item.status==="active").length}</strong><small>{teachers.length} teachers</small></article><article><span>ARR</span><strong>{money.format(arr)}</strong><small>{commercial?.contract_status||"Commercials pending"}</small></article></section>
  <div className="school-detail-grid"><section className="card"><header className="card-header"><div><h2>School profile</h2><p>Identity, regulatory, support and web presence.</p></div><span className={`status ${school.onboarding_stage==="live"?"":"status-warning"}`}>{school.onboarding_stage}</span></header><dl className="detail-list"><div><dt>Website</dt><dd>{school.website_url?<a href={school.website_url} target="_blank" rel="noreferrer">{school.website_url} ↗</a>:"Not supplied"}</dd></div><div><dt>Established</dt><dd>{school.established_year||"Not supplied"}</dd></div><div><dt>Affiliation</dt><dd>{school.affiliation_number||"Not supplied"}</dd></div><div><dt>School contact</dt><dd>{school.primary_email||"—"}<br/>{school.primary_phone||"—"}</dd></div><div><dt>Customer success</dt><dd>{school.customer_success_owner||"Unassigned"}</dd></div><div><dt>Go-live</dt><dd>{school.go_live_on||"Pending"}</dd></div></dl></section><section className="card"><header className="card-header"><div><h2>Commercial profile</h2><p>Subscription, capacity, term and recurring value.</p></div></header><dl className="detail-list"><div><dt>Plan</dt><dd>{commercial?.plan_name||"Not configured"}</dd></div><div><dt>Billing</dt><dd>{commercial?.billing_cycle||"—"}</dd></div><div><dt>Recurring amount</dt><dd>{commercial?money.format(Number(commercial.recurring_amount)):"—"}</dd></div><div><dt>Implementation fee</dt><dd>{commercial?money.format(Number(commercial.implementation_fee)):"—"}</dd></div><div><dt>Contract term</dt><dd>{commercial?.contract_starts_on||"—"} → {commercial?.contract_ends_on||"—"}</dd></div></dl></section></div>
  <section className="card"><header className="card-header"><div><h2>Branches and exact locations</h2><p>Operational headcount is calculated from current records.</p></div><span className="status">{branches.length} BRANCHES</span></header><div className="branch-grid">{branches.map(branch=>{const branchStudents=students.filter(item=>item.campus_id===branch.id&&item.status==="active").length,branchStaff=staff.filter(item=>item.campus_id===branch.id&&item.status==="active").length;const map=branch.latitude!=null&&branch.longitude!=null?`https://www.google.com/maps?q=${branch.latitude},${branch.longitude}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([branch.address_line1,branch.city,branch.state,branch.postal_code].filter(Boolean).join(", "))}`;return <article key={branch.id}><div><span className="status">{branch.code}</span><h3>{branch.name}</h3><p>{[branch.address_line1,branch.address_line2,branch.city,branch.state,branch.postal_code,branch.country].filter(Boolean).join(", ")}</p><a href={map} target="_blank" rel="noreferrer">Open exact location ↗</a></div><dl><div><dt>Students</dt><dd>{branchStudents}</dd></div><div><dt>Staff</dt><dd>{branchStaff}</dd></div><div><dt>Contact</dt><dd>{branch.email||branch.phone||"—"}</dd></div></dl></article>})}</div></section>
  <section className="card owner-directory"><header className="card-header"><div><h2>Accountable owners</h2><p>Everyone with tenant-wide school owner rights.</p></div></header><div className="owner-table">{(ownerMembershipsResult.data||[]).map(membership=>{const owner=(ownersResult.data||[]).find(item=>item.user_id===membership.user_id),person=users.get(membership.user_id);return <div className="owner-row detail-owner-row" key={membership.user_id}><span><b>{String(person?.user_metadata?.full_name||"School owner")}</b><small>{owner?.is_primary!==false?"Primary owner":"Additional owner"}</small></span><span><b>{person?.email||"—"}</b><small>{owner?.phone||"No phone"}</small></span><span><b>{owner?.job_title||"School owner"}</b><small>{person?.email_confirmed_at?"Account active":"Invitation pending"}</small></span></div>})}</div></section>
  </div></main>;
}
