import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { InvoiceForm, PaymentForm } from "@/components/finance/finance-forms";
import { getUserContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";

function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});
export default async function FinancePage(){const context=await getUserContext();if(!context)redirect("/login?next=/dashboard/finance");const supabase=await createClient();if(!supabase)redirect("/login");const manager=["owner","administrator","principal","staff"].includes(context.role);
 const [studentsResult,invoicesResult]=await Promise.all([supabase.from("students").select("id,first_name,last_name,admission_number").eq("organization_id",context.organizationId).eq("status","active").order("first_name").limit(1000),supabase.from("fee_invoices").select("id,student_id,fee_name,amount,paid_amount,due_on,status,notes").eq("organization_id",context.organizationId).order("due_on",{ascending:false}).limit(200)]);if(studentsResult.error||invoicesResult.error)throw new Error("Fee information could not be loaded.");const students=studentsResult.data||[];const names=new Map(students.map(s=>[s.id,`${s.first_name} ${s.last_name||""}`.trim()]));const invoices=invoicesResult.data||[];const due=invoices.filter(i=>["due","partial"].includes(i.status)).reduce((sum,i)=>sum+Number(i.amount)-Number(i.paid_amount),0),collected=invoices.reduce((sum,i)=>sum+Number(i.paid_amount),0);
 return <AppShell context={context} activePath="/dashboard/finance" pageTitle="Finance"><div className="page-head"><div><span className="eyebrow">FEES & RECEIPTS</span><h1>Every due. Every payment.</h1><p>{manager?"Create student invoices and record verified offline collections.":"View fee dues and payments recorded by the school."}</p></div></div><section className="student-metrics"><div><span>Invoices</span><strong>{invoices.length}</strong><small>Visible records</small></div><div><span>Outstanding</span><strong>{money.format(due)}</strong><small>Due and partial</small></div><div><span>Collected</span><strong>{money.format(collected)}</strong><small>Recorded payments</small></div><div><span>Online payment</span><strong>—</strong><small>Gateway unavailable</small></div></section><div className={`workflow-layout ${manager?"":"workflow-single"}`}><section className="card"><header className="card-header"><div><h2>Fee ledger</h2><p>Amounts and payment status by student.</p></div></header><div className="invoice-list">{invoices.map(i=>{const outstanding=Number(i.amount)-Number(i.paid_amount);return <details key={i.id}><summary><div><b>{i.fee_name}</b><small>{names.get(i.student_id)||"Student"} · Due {i.due_on}</small></div><strong>{money.format(outstanding)}</strong><span className={`status ${i.status==="due"||i.status==="partial"?"status-warning":""}`}>{i.status}</span></summary><div className="invoice-detail"><p>Total {money.format(Number(i.amount))} · Paid {money.format(Number(i.paid_amount))}</p>{i.notes&&<p>{i.notes}</p>}{manager&&outstanding>0&&<PaymentForm invoiceId={i.id} outstanding={outstanding}/>}</div></details>})}{!invoices.length&&<p className="empty-copy task-empty">No fee invoices are visible.</p>}</div></section>{manager&&<aside className="card"><header className="card-header"><div><h2>Create invoice</h2><p>Online payment remains unavailable until a gateway is configured.</p></div></header><div className="card-body"><InvoiceForm today={today()} students={students.map(s=>({id:s.id,label:`${names.get(s.id)} · ${s.admission_number}`}))}/></div></aside>}</div></AppShell>}
