import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { PeriodForm, TemplateForm } from "@/components/reporting/report-config-forms";
import { getUserContext } from "@/lib/auth/context";
import { dateLabel, percentage } from "@/lib/reporting";
import { createClient } from "@/lib/supabase/server";
import { initializeClassReports } from "./actions";

type Search = { view?: string; period?: string; student?: string; error?: string };

export default async function ReportCardsPage({ searchParams }: { searchParams: Promise<Search> }) {
  const context = await getUserContext(); if (!context) redirect("/login?next=/dashboard/report-cards");
  const query = await searchParams;
  if (["parent","student"].includes(context.role)) return <FamilyRecords query={query}/>;
  const supabase = await createClient(); if (!supabase) redirect("/login");
  const leader = ["owner","administrator","principal"].includes(context.role), teacher = context.role === "teacher", canInitialize = leader || context.role === "staff";
  const [templatesResult, periodsResult, yearsResult, classesResult, staffResult, allocationsResult, cardsResult, rowsResult] = await Promise.all([
    supabase.from("report_card_templates").select("id,name,title,grading_scale,status,show_percentage,show_attendance,show_teacher_comments").eq("organization_id",context.organizationId).order("created_at",{ascending:false}),
    supabase.from("reporting_periods").select("id,academic_year_id,template_id,name,starts_on,ends_on,status").eq("organization_id",context.organizationId).order("starts_on",{ascending:false}),
    supabase.from("academic_years").select("id,name,status").eq("organization_id",context.organizationId).order("starts_on",{ascending:false}),
    supabase.from("classes").select("id,academic_year_id,grade,section,campus_id").eq("organization_id",context.organizationId).order("grade").limit(500),
    supabase.from("staff_profiles").select("id").eq("organization_id",context.organizationId).eq("user_id",context.userId).maybeSingle(),
    supabase.from("class_subjects").select("id,class_id,teacher_staff_id").eq("organization_id",context.organizationId).limit(5000),
    supabase.from("report_cards").select("id,period_id,class_id,student_id,status,overall_comment").eq("organization_id",context.organizationId).limit(20000),
    supabase.from("report_card_subjects").select("report_card_id,class_subject_id,grade").eq("organization_id",context.organizationId).limit(50000),
  ]);
  if ([templatesResult,periodsResult,yearsResult,classesResult,staffResult,allocationsResult,cardsResult,rowsResult].some((result)=>result.error)) throw new Error("Formal reporting data could not be loaded. Apply the reporting migration if this is the first deployment.");
  const templates=templatesResult.data||[],periods=periodsResult.data||[],years=yearsResult.data||[],allAllocations=allocationsResult.data||[];
  const allowedClassIds=new Set(teacher?allAllocations.filter((row)=>row.teacher_staff_id===staffResult.data?.id).map((row)=>row.class_id):(classesResult.data||[]).map((row)=>row.id));
  const classes=(classesResult.data||[]).filter((row)=>allowedClassIds.has(row.id));
  const cards=(cardsResult.data||[]).filter((row)=>allowedClassIds.has(row.class_id));
  const cardIds=new Set(cards.map((row)=>row.id)),rows=(rowsResult.data||[]).filter((row)=>cardIds.has(row.report_card_id));
  const selectedPeriod=periods.find((row)=>row.id===query.period)||periods[0];
  const requestedView=["periods","templates","archive"].includes(query.view||"")?query.view!:"periods";
  const view=requestedView==="templates"&&!leader?"periods":requestedView;
  const periodCards=selectedPeriod?cards.filter((row)=>row.period_id===selectedPeriod.id):[];
  const rowByCard=new Map<string,typeof rows>();for(const row of rows)rowByCard.set(row.report_card_id,[...(rowByCard.get(row.report_card_id)||[]),row]);
  const statusCounts=new Map<string,number>();for(const card of periodCards)statusCounts.set(card.status,(statusCounts.get(card.status)||0)+1);
  return <AppShell context={context} activePath="/dashboard/report-cards" pageTitle="Report cards">
    <div className="page-head"><div><span className="eyebrow">FORMAL ACADEMIC RECORDS</span><h1>Complete together. Publish with confidence.</h1><p>Subject teachers contribute once, leaders review the whole class, and families see only approved published records.</p></div>{selectedPeriod&&<span className={`status ${selectedPeriod.status!=="open"?"status-warning":""}`}>{selectedPeriod.name} · {selectedPeriod.status}</span>}</div>
    {query.error&&<p className="form-error admin-message" role="alert">{query.error}</p>}
    <section className="formal-kpis"><article><span>Report cards</span><strong>{periodCards.length}</strong><small>generated in this period</small></article><article><span>Draft</span><strong>{statusCounts.get("draft")||0}</strong><small>open for contribution</small></article><article><span>In review</span><strong>{(statusCounts.get("submitted")||0)+(statusCounts.get("approved")||0)}</strong><small>submitted or approved</small></article><article><span>Published</span><strong>{statusCounts.get("published")||0}</strong><small>visible to families</small></article></section>
    <nav className="platform-tabs formal-tabs" aria-label="Formal reporting sections"><Link href="/dashboard/report-cards?view=periods" className={view==="periods"?"active":""}>Reporting periods</Link>{leader&&<Link href="/dashboard/report-cards?view=templates" className={view==="templates"?"active":""}>Templates</Link>}<Link href="/dashboard/report-cards?view=archive" className={view==="archive"?"active":""}>Published archive</Link></nav>
    {view==="periods"&&<div className="formal-workspace"><section className="card"><header className="card-header"><div><h2>Class completion</h2><p>Open a class to complete subject grades, overall comments and the review workflow.</p></div>{periods.length>1&&<nav className="period-switcher">{periods.filter((row)=>row.status!=="closed").map((row)=><Link key={row.id} className={row.id===selectedPeriod?.id?"active":""} href={`/dashboard/report-cards?period=${row.id}`}>{row.name}</Link>)}</nav>}</header><div className="formal-class-list">{selectedPeriod&&classes.filter((row)=>row.academic_year_id===selectedPeriod.academic_year_id).map((schoolClass)=>{const classCards=periodCards.filter((row)=>row.class_id===schoolClass.id),classCardIds=new Set(classCards.map((row)=>row.id)),classRows=rows.filter((row)=>classCardIds.has(row.report_card_id)),complete=classRows.filter((row)=>row.grade).length,expected=classRows.length,status=classCards[0]?.status||"not started";return <article key={schoolClass.id}><span className="class-token">{schoolClass.grade}<small>{schoolClass.section}</small></span><div><b>{schoolClass.grade} · Section {schoolClass.section}</b><small>{classCards.length} students · {complete}/{expected} subject grades</small><div className="progress-track"><span style={{width:`${percentage(complete,expected)||0}%`}}/></div></div><span className={`status ${["not started","draft","submitted"].includes(status)?"status-warning":""}`}>{status}</span>{classCards.length?<Link href={`/dashboard/report-cards/${selectedPeriod.id}/classes/${schoolClass.id}`}>Open →</Link>:canInitialize?<form action={initializeClassReports}><input type="hidden" name="period_id" value={selectedPeriod.id}/><input type="hidden" name="class_id" value={schoolClass.id}/><button className="secondary compact">Generate</button></form>:<small>Awaiting school setup</small>}</article>})}{!selectedPeriod&&<div className="report-empty"><span>▤</span><b>No reporting period</b><p>{leader?"Create a template and reporting period to begin.":"A school leader must open a reporting period."}</p></div>}</div></section>{leader&&<aside className="card"><header className="card-header"><div><h2>New reporting period</h2><p>Connect one academic year to one approved format.</p></div></header><div className="card-body"><PeriodForm years={years.map((row)=>({id:row.id,name:row.name}))} templates={templates.filter((row)=>row.status==="active").map((row)=>({id:row.id,name:row.name}))}/></div></aside>}</div>}
    {view==="templates"&&leader&&<div className="formal-workspace"><section className="card"><header className="card-header"><div><h2>Template library</h2><p>Stable presentation rules shared by every card in a period.</p></div><span className="status">{templates.length}</span></header><div className="template-list">{templates.map((row)=><article key={row.id}><div><b>{row.name}</b><small>{row.title}</small></div><span className="status">{row.status}</span><small>{Array.isArray(row.grading_scale)?row.grading_scale.length:0} grade bands · {row.show_percentage?"percentage shown":"grade only"}</small></article>)}</div></section><aside className="card"><header className="card-header"><div><h2>Create template</h2><p>Set the printed title, scale and visible sections.</p></div></header><div className="card-body"><TemplateForm/></div></aside></div>}
    {view==="archive"&&<section className="card tab-panel"><header className="card-header"><div><h2>Published archive</h2><p>Immutable family-visible records and printable cards.</p></div></header><div className="published-card-list">{cards.filter((row)=>row.status==="published").map((card)=>{const schoolClass=classes.find((row)=>row.id===card.class_id),period=periods.find((row)=>row.id===card.period_id);return <Link key={card.id} href={`/dashboard/report-cards/${card.id}/print`}><span>▤</span><div><b>{period?.name||"Report card"}</b><small>{schoolClass?`${schoolClass.grade} · Section ${schoolClass.section}`:"Class"}</small></div><strong>Open →</strong></Link>})}{!cards.some((row)=>row.status==="published")&&<div className="report-empty"><span>◎</span><b>No published cards yet</b><p>Approved class reports will appear here after publication.</p></div>}</div></section>}
  </AppShell>;
}

async function FamilyRecords({ query }: { query: Search }) {
  const context=await getUserContext();const supabase=await createClient();if(!context||!supabase)redirect("/login");
  const studentsResult=await supabase.from("students").select("id,first_name,last_name,preferred_name,admission_number").eq("organization_id",context.organizationId).eq("status","active").order("first_name");if(studentsResult.error)throw new Error("Linked students could not be loaded.");
  const students=studentsResult.data||[],student=students.find((row)=>row.id===query.student)||students[0];
  if(!student)return <AppShell context={context} activePath="/dashboard/report-cards" pageTitle="Report cards"><section className="card card-body"><h1>No student is linked yet</h1><p>Ask the school office to connect this account to a student record.</p></section></AppShell>;
  const [cardsResult,periodsResult,classesResult]=await Promise.all([supabase.from("report_cards").select("id,period_id,class_id,status,published_at").eq("student_id",student.id).eq("status","published").order("published_at",{ascending:false}),supabase.from("reporting_periods").select("id,name,starts_on,ends_on").eq("organization_id",context.organizationId),supabase.from("classes").select("id,grade,section").eq("organization_id",context.organizationId)]);if(cardsResult.error||periodsResult.error||classesResult.error)throw new Error("Published report cards could not be loaded.");
  const periods=new Map((periodsResult.data||[]).map((row)=>[row.id,row])),classes=new Map((classesResult.data||[]).map((row)=>[row.id,row])),cards=cardsResult.data||[];
  return <AppShell context={context} activePath="/dashboard/report-cards" pageTitle="Report cards"><div className="page-head"><div><span className="eyebrow">PUBLISHED ACADEMIC RECORDS</span><h1>{context.role==="student"?"Your":`${student.preferred_name||student.first_name}’s`} report cards.</h1><p>Only records reviewed and published by the school appear here.</p></div><Link className="secondary compact" href={`/dashboard/report-cards/transcript/${student.id}`}><span>Open transcript</span><span>→</span></Link></div>{students.length>1&&<nav className="student-switcher report-student-switcher">{students.map((row)=><Link key={row.id} className={row.id===student.id?"active":""} href={`/dashboard/report-cards?student=${row.id}`}>{row.preferred_name||row.first_name}</Link>)}</nav>}<section className="card"><header className="card-header"><div><h2>Published records</h2><p>Open a card to print or save it as a PDF.</p></div><span className="status">{cards.length}</span></header><div className="published-card-list">{cards.map((card)=>{const period=periods.get(card.period_id),schoolClass=classes.get(card.class_id);return <Link href={`/dashboard/report-cards/${card.id}/print`} key={card.id}><span>▤</span><div><b>{period?.name||"Report card"}</b><small>{schoolClass?`${schoolClass.grade} · Section ${schoolClass.section}`:"Class"} · {period?`${dateLabel(period.starts_on)} - ${dateLabel(period.ends_on)}`:"Published"}</small></div><strong>Open →</strong></Link>})}{!cards.length&&<div className="report-empty"><span>◎</span><b>No report cards published yet</b><p>The school will publish completed records here after review.</p></div>}</div></section></AppShell>;
}
