import Link from "next/link";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { SubmissionForm } from "@/components/learning/submission-form";
import { getUserContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";

export default async function LearningPage({searchParams}:{searchParams:Promise<{student?:string}>}){
 const context=await getUserContext();if(!context)redirect("/login?next=/dashboard/learning");if(!["parent","student"].includes(context.role))redirect("/dashboard");const supabase=await createClient();if(!supabase)redirect("/login");
 const studentsResult=await supabase.from("students").select("id,first_name,last_name,preferred_name,admission_number").eq("organization_id",context.organizationId).eq("status","active").order("first_name");if(studentsResult.error)throw new Error("Linked students could not be loaded.");const students=studentsResult.data||[];const requested=(await searchParams).student;const student=students.find(s=>s.id===requested)||students[0];
 if(!student)return <AppShell context={context} activePath="/dashboard/learning" pageTitle="My learning"><section className="card card-body"><h1>No student is linked yet</h1><p>Ask the school office to connect this account to a student record.</p></section></AppShell>;
 const [enrollmentsResult,submissionsResult,marksResult,recordsResult,invoicesResult]=await Promise.all([
  supabase.from("class_enrollments").select("class_id").eq("organization_id",context.organizationId).eq("student_id",student.id).eq("status","active"),
  supabase.from("homework_submissions").select("homework_id,response,status,feedback").eq("organization_id",context.organizationId).eq("student_id",student.id),
  supabase.from("assessment_marks").select("assessment_id,marks,result_status,note").eq("organization_id",context.organizationId).eq("student_id",student.id),
  supabase.from("attendance_records").select("session_id,status").eq("organization_id",context.organizationId).eq("student_id",student.id).limit(500),
  supabase.from("fee_invoices").select("id,amount,paid_amount,status,due_on").eq("organization_id",context.organizationId).eq("student_id",student.id).not("status","in","(waived,cancelled)")
 ]);if([enrollmentsResult,submissionsResult,marksResult,recordsResult,invoicesResult].some(r=>r.error))throw new Error("Student learning data could not be loaded.");
 const classIds=(enrollmentsResult.data||[]).map(e=>e.class_id);let homeworkClasses:{homework_id:string}[]=[];let allocations:{id:string;subject_id:string}[]=[];if(classIds.length){const [hc,cs]=await Promise.all([supabase.from("homework_classes").select("homework_id").in("class_id",classIds),supabase.from("class_subjects").select("id,subject_id").in("class_id",classIds)]);if(hc.error||cs.error)throw new Error("Assigned work could not be loaded.");homeworkClasses=hc.data||[];allocations=cs.data||[];}
 const homeworkIds=[...new Set(homeworkClasses.map(h=>h.homework_id))],assessmentIds=(marksResult.data||[]).map(m=>m.assessment_id);const [homeworkResult,assessmentsResult,subjectsResult]=await Promise.all([
  homeworkIds.length?supabase.from("homework_assignments").select("id,subject_id,title,instructions,due_at,estimated_minutes,status").in("id",homeworkIds).eq("status","published").order("due_at"):{data:[],error:null},
  assessmentIds.length?supabase.from("assessments").select("id,class_subject_id,title,assessment_date,max_marks,status").in("id",assessmentIds).eq("status","published").order("assessment_date",{ascending:false}):{data:[],error:null},
  supabase.from("subjects").select("id,name,code").eq("organization_id",context.organizationId)
 ]);if(homeworkResult.error||assessmentsResult.error||subjectsResult.error)throw new Error("Published learning data could not be loaded.");
 const subjectMap=new Map((subjectsResult.data||[]).map(s=>[s.id,s]));const submissionMap=new Map((submissionsResult.data||[]).map(s=>[s.homework_id,s]));const markMap=new Map((marksResult.data||[]).map(m=>[m.assessment_id,m]));const allocationMap=new Map(allocations.map(a=>[a.id,a]));const attendance=recordsResult.data||[];const present=attendance.filter(r=>["present","late"].includes(r.status)).length;const attendanceRate=attendance.length?Math.round(present/attendance.length*100):null;const outstanding=(invoicesResult.data||[]).reduce((sum,i)=>sum+Number(i.amount)-Number(i.paid_amount),0);const openHomework=(homeworkResult.data||[]).filter(h=>!["submitted","completed"].includes(submissionMap.get(h.id)?.status||"")).length;
 const displayName=student.preferred_name||student.first_name;
 return <AppShell context={context} activePath="/dashboard/learning" pageTitle="My learning"><div className="page-head"><div><span className="eyebrow">FAMILY & STUDENT PORTAL</span><h1>{displayName}’s school day.</h1><p>Homework, published results, attendance, notices and fees in one place.</p></div>{students.length>1&&<nav className="student-switcher" aria-label="Select student">{students.map(s=><Link className={s.id===student.id?"active":""} href={`/dashboard/learning?student=${s.id}`} key={s.id}>{s.preferred_name||s.first_name}</Link>)}</nav>}</div>
 <section className="student-metrics"><a href="#homework"><span>Homework open</span><strong>{openHomework}</strong><small>View assignments ↓</small></a><a href="#results"><span>Attendance</span><strong>{attendanceRate===null?"—":`${attendanceRate}%`}</strong><small>{attendance.length} recorded days</small></a><a href="#results"><span>Published results</span><strong>{assessmentsResult.data?.length||0}</strong><small>View progress ↓</small></a><Link href="/dashboard/finance"><span>Fees outstanding</span><strong>{new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(outstanding)}</strong><small>View fee ledger →</small></Link></section>
 <div className="student-grid"><section className="card" id="homework"><header className="card-header"><div><h2>Homework</h2><p>Published assignments for the current class.</p></div></header><div className="family-homework">{(homeworkResult.data||[]).map(h=>{const submission=submissionMap.get(h.id),subject=subjectMap.get(h.subject_id);return <details key={h.id}><summary><span className="assessment-icon">{subject?.code.slice(0,3)||"HW"}</span><span><b>{h.title}</b><small>{subject?.name||"Subject"} · Due {new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeZone:"Asia/Kolkata"}).format(new Date(h.due_at))}</small></span><span className={`status ${submission?.status==="submitted"||submission?.status==="completed"?"":"status-warning"}`}>{submission?.status?.replace("_"," ")||"open"}</span></summary><div className="assignment-body"><p>{h.instructions}</p><SubmissionForm homeworkId={h.id} studentId={student.id} initialResponse={submission?.response} initialStatus={submission?.status}/>{submission?.feedback&&<p className="feedback"><b>Teacher feedback:</b> {submission.feedback}</p>}</div></details>})}{!homeworkResult.data?.length&&<p className="empty-copy task-empty">No published homework is due.</p>}</div></section>
 <aside className="card" id="results"><header className="card-header"><div><h2>Results</h2><p>Only results published by the school.</p></div></header><div className="result-list">{(assessmentsResult.data||[]).map(a=>{const mark=markMap.get(a.id),allocation=allocationMap.get(a.class_subject_id),subject=allocation?subjectMap.get(allocation.subject_id):null;const score=mark?.result_status==="scored"?`${mark.marks} / ${a.max_marks}`:mark?.result_status?.replace("_"," ");return <article key={a.id}><span className="assessment-icon">{subject?.code.slice(0,3)||"ASM"}</span><div><b>{a.title}</b><small>{subject?.name||"Subject"} · {a.assessment_date}</small>{mark?.note&&<p>{mark.note}</p>}</div><strong>{score||"—"}</strong></article>})}{!assessmentsResult.data?.length&&<p className="empty-copy task-empty">No results have been published.</p>}</div></aside></div>
 </AppShell>;
}
