import { redirect } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { LeaveForm } from "@/components/approvals/leave-form";
import { getUserContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { reviewAttendanceCorrection, reviewLeaveRequest } from "./actions";

function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
export default async function ApprovalsPage(){
 const context=await getUserContext();if(!context)redirect("/login?next=/dashboard/approvals");const supabase=await createClient();if(!supabase)redirect("/login");const manager=["owner","administrator","principal","staff"].includes(context.role);
 const [studentsResult,staffResult,requestsResult,correctionsResult,recordsResult,sessionsResult]=await Promise.all([
  supabase.from("students").select("id,first_name,last_name,admission_number").eq("organization_id",context.organizationId).eq("status","active").order("first_name").limit(1000),
  supabase.from("staff_profiles").select("id,first_name,last_name,employee_number,user_id").eq("organization_id",context.organizationId).eq("status","active").order("first_name").limit(1000),
  supabase.from("leave_requests").select("id,student_id,staff_id,leave_type,starts_on,ends_on,reason,status,review_note,created_at").eq("organization_id",context.organizationId).order("created_at",{ascending:false}).limit(100),
  supabase.from("attendance_corrections").select("id,attendance_record_id,requested_status,reason,status,created_at").eq("organization_id",context.organizationId).eq("status","pending").order("created_at").limit(100),
  supabase.from("attendance_records").select("id,session_id,student_id,status").eq("organization_id",context.organizationId),
  supabase.from("attendance_sessions").select("id,attendance_date").eq("organization_id",context.organizationId)
 ]);if(studentsResult.error||staffResult.error||requestsResult.error||correctionsResult.error||recordsResult.error||sessionsResult.error)throw new Error("Approval requests could not be loaded.");
 const students=studentsResult.data||[],staff=staffResult.data||[];const studentMap=new Map(students.map(s=>[s.id,`${s.first_name} ${s.last_name||""}`.trim()]));const staffMap=new Map(staff.map(s=>[s.id,`${s.first_name} ${s.last_name||""}`.trim()]));
 const people=manager?[...students.map(s=>({id:s.id,type:"student" as const,label:`${studentMap.get(s.id)} · ${s.admission_number}`})),...staff.map(s=>({id:s.id,type:"staff" as const,label:`${staffMap.get(s.id)} · ${s.employee_number}`}))]:[...students.map(s=>({id:s.id,type:"student" as const,label:studentMap.get(s.id)!})),...staff.filter(s=>s.user_id===context.userId).map(s=>({id:s.id,type:"staff" as const,label:staffMap.get(s.id)!}))];
 const pending=(requestsResult.data||[]).filter(r=>r.status==="pending"),history=(requestsResult.data||[]).filter(r=>r.status!=="pending");const recordMap=new Map((recordsResult.data||[]).map(r=>[r.id,r])),sessionMap=new Map((sessionsResult.data||[]).map(s=>[s.id,s]));
 const requestCard=(item:(typeof requestsResult.data)[number],review:boolean)=><article className="request-row" key={item.id}><div><span className="status status-warning">{item.leave_type}</span><h3>{item.student_id?studentMap.get(item.student_id):item.staff_id?staffMap.get(item.staff_id):"Person"}</h3><p>{item.starts_on} to {item.ends_on} · {item.reason}</p>{item.review_note&&<small>Review note: {item.review_note}</small>}</div>{review?<form action={reviewLeaveRequest} className="decision-form"><input type="hidden" name="request_id" value={item.id}/><input name="review_note" aria-label="Review note" maxLength={500} placeholder="Optional note"/><button name="decision" value="approved" className="secondary">Approve</button><button name="decision" value="rejected" className="secondary danger-button">Reject</button></form>:<span className={`status ${item.status==="rejected"?"status-danger":""}`}>{item.status}</span>}</article>;
 return <AppShell context={context} activePath="/dashboard/approvals" pageTitle="Approvals"><div className="page-head"><div><span className="eyebrow">REQUESTS & DECISIONS</span><h1>Ask once. Track every decision.</h1><p>Leave and attendance corrections stay visible from submission through review.</p></div></div>{manager&&Boolean(correctionsResult.data?.length)&&<section className="card correction-card"><header className="card-header"><div><h2>Attendance corrections</h2><p>Approving changes the original attendance record and records the reviewer.</p></div><span className="status status-warning">{correctionsResult.data?.length} pending</span></header><div className="request-list">{correctionsResult.data?.map(c=>{const record=recordMap.get(c.attendance_record_id),session=record?sessionMap.get(record.session_id):null;return <article className="request-row" key={c.id}><div><span className="status status-warning">{record?.status||"Recorded"} → {c.requested_status}</span><h3>{record?studentMap.get(record.student_id)||"Student":"Attendance record correction"}</h3><p>{session?.attendance_date?`${session.attendance_date} · `:""}{c.reason}</p></div><form action={reviewAttendanceCorrection} className="decision-form compact-decision"><input type="hidden" name="correction_id" value={c.id}/><button name="decision" value="approved" className="secondary">Approve</button><button name="decision" value="rejected" className="secondary danger-button">Reject</button></form></article>})}</div></section>}<div className="workflow-layout"><section className="card"><header className="card-header"><div><h2>{manager?"Pending leave":"My requests"}</h2><p>{manager?"Oldest requests should be handled first.":"Your latest leave request status."}</p></div><span className="status">{pending.length} pending</span></header><div className="request-list">{(manager?pending:requestsResult.data||[]).map(r=>requestCard(r,manager))}{!(manager?pending:requestsResult.data||[]).length&&<p className="empty-copy task-empty">No requests need attention.</p>}</div>{manager&&history.length>0&&<details className="history-panel"><summary>Decision history ({history.length})</summary><div className="request-list">{history.map(r=>requestCard(r,false))}</div></details>}</section><aside className="card"><header className="card-header"><div><h2>Request leave</h2><p>Submit for a linked student or staff member.</p></div></header><div className="card-body"><LeaveForm people={people} today={today()}/></div></aside></div></AppShell>;
}
