"use client";
import { useActionState,useMemo,useState } from "react";
import { assignStudent,createRoute,createStop,createVehicle,publishTransportAlert,type TransportState } from "@/app/dashboard/transport/actions";
const initial={} as TransportState;
export function VehicleForm({campuses}:{campuses:{id:string;name:string}[]}){const[s,a,p]=useActionState(createVehicle,initial);return <form className="workflow-form" action={a}><label className="field">Campus<select name="campus_id" required>{campuses.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><div className="form-two"><label className="field">Vehicle name<input name="label" required placeholder="Bus 12"/></label><label className="field">Registration<input name="registration_number" required placeholder="KA 01 AB 1234"/></label></div><label className="field">Capacity<input name="capacity" type="number" min="1" max="100" defaultValue="40" required/></label><div className="form-two"><label className="field">Driver name<input name="driver_name"/></label><label className="field">Driver phone<input name="driver_phone" inputMode="tel"/></label></div><Message state={s}/><button className="primary" disabled={p}>Add vehicle</button></form>}
export function RouteForm({campuses,vehicles}:{campuses:{id:string;name:string}[];vehicles:{id:string;label:string}[]}){const[s,a,p]=useActionState(createRoute,initial);return <form className="workflow-form" action={a}><label className="field">Campus<select name="campus_id" required>{campuses.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="field">Vehicle<select name="vehicle_id"><option value="">Assign later</option>{vehicles.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><div className="form-two"><label className="field">Route name<input name="name" required placeholder="Koramangala East"/></label><label className="field">Code<input name="code" required placeholder="R12"/></label></div><div className="form-two"><label className="field">Morning departure<input name="morning_departure" type="time"/></label><label className="field">Afternoon departure<input name="afternoon_departure" type="time"/></label></div><Message state={s}/><button className="primary" disabled={p}>Create route</button></form>}
export function StopForm({routes}:{routes:{id:string;name:string}[]}){const[s,a,p]=useActionState(createStop,initial);return <form className="inline-workflow" action={a}><label className="field">Route<select name="route_id" required>{routes.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="field">Stop name<input name="name" required/></label><label className="field">Order<input name="stop_order" type="number" min="1" max="200" required/></label><label className="field">Pickup<input name="pickup_time" type="time"/></label><label className="field">Drop<input name="drop_time" type="time"/></label><Message state={s}/><button className="secondary" disabled={p}>Add stop</button></form>}
export function AssignmentForm({students,routes,stops,today}:{students:{id:string;label:string}[];routes:{id:string;name:string}[];stops:{id:string;route_id:string;name:string}[];today:string}){const[s,a,p]=useActionState(assignStudent,initial),[route,setRoute]=useState(routes[0]?.id||"");const choices=useMemo(()=>stops.filter(x=>x.route_id===route),[stops,route]);return <form className="inline-workflow assignment-form" action={a}><label className="field">Student<select name="student_id" required>{students.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><label className="field">Route<select name="route_id" value={route} onChange={e=>setRoute(e.target.value)} required>{routes.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="field">Stop<select name="stop_id" required>{choices.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="field">Starts<input name="starts_on" type="date" defaultValue={today} required/></label><Message state={s}/><button className="secondary" disabled={p||!choices.length}>Assign student</button></form>}
export function AlertForm({routes}:{routes:{id:string;name:string}[]}){const[s,a,p]=useActionState(publishTransportAlert,initial);return <form className="inline-workflow alert-form" action={a}><label className="field">Route<select name="route_id" required>{routes.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="field">Severity<select name="severity"><option value="delay">Delay</option><option value="info">Information</option><option value="critical">Critical</option></select></label><label className="field">Title<input name="title" required/></label><label className="field form-grow">Message<input name="message" required maxLength={1000}/></label><Message state={s}/><button className="secondary" disabled={p}>Publish alert</button></form>}
function Message({state}:{state:TransportState}){return <>{state.error&&<p className="form-error" role="alert">{state.error}</p>}{state.success&&<p className="form-success" role="status">{state.success}</p>}</>}
